<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="de_DE">
<context>
    <name>AboutDialog</name>
    <message>
        <source>About gta5sync</source>
        <translation type="vanished">Über gta5sync</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;
&lt;br/&gt;
A project for viewing and sync Grand Theft Auto V Snapmatic&lt;br/&gt;
Pictures and Savegames&lt;br/&gt;
&lt;br/&gt;
Project version: %1&lt;br/&gt;
Project build: %4, %5&lt;br/&gt;
Compiled with Qt %2&lt;br/&gt;
Running with Qt %3&lt;br/&gt;
&lt;br/&gt;
Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation type="vanished">&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;
&lt;br/&gt;
Ein Projekt zum ansehen und synchronisieren von&lt;br/&gt;
Grand Theft Auto V Snapmatic Bilder und Spielständen&lt;br/&gt;
&lt;br/&gt;
Projektversion: %1&lt;br/&gt;
Projektbau: %4, %5&lt;br/&gt;
Gebaut mit Qt %2&lt;br/&gt;
Läuft auf Qt %3&lt;br/&gt;
&lt;br/&gt;
Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync ist lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;
&lt;br/&gt;
A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;
&lt;br/&gt;
Project version: %1&lt;br/&gt;
Project build: %4, %5&lt;br/&gt;
Compiled with Qt %2&lt;br/&gt;
Running with Qt %3&lt;br/&gt;
&lt;br/&gt;
Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation type="vanished">&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;
&lt;br/&gt;
Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;
&lt;br/&gt;
Projektversion: %1&lt;br/&gt;
Projektbau: %4, %5&lt;br/&gt;
Gebaut mit Qt %2&lt;br/&gt;
Läuft auf Qt %3&lt;br/&gt;
&lt;br/&gt;
Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="14"/>
        <source>About %1</source>
        <translation>Über %1</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="29"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;%8&lt;/span&gt;&lt;br/&gt;
&lt;br/&gt;
%9&lt;br/&gt;
&lt;br/&gt;
Project version: %1&lt;br/&gt;
Project build: %4&lt;br/&gt;
Compiled with Qt %2&lt;br/&gt;
Running with Qt %3&lt;br/&gt;
&lt;br/&gt;
Copyright &amp;copy; &lt;a href=&quot;%5&quot;&gt;%6&lt;/a&gt; %7&lt;br/&gt;%8 is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;%8&lt;/span&gt;&lt;br/&gt;
&lt;br/&gt;
%9&lt;br/&gt;
&lt;br/&gt;
Projektversion: %1&lt;br/&gt;
Projektbau: %4&lt;br/&gt;
Gebaut mit Qt %2&lt;br/&gt;
Läuft auf Qt %3&lt;br/&gt;
&lt;br/&gt;
Copyright &amp;copy; &lt;a href=&quot;%5&quot;&gt;%6&lt;/a&gt; %7&lt;br/&gt;%8 ist lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="75"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>generated by class</source>
        <translation type="obsolete">Generiert von der Klasse</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;&lt;br/&gt;Project version: %1&lt;br/&gt;Compiled with Qt %2&lt;br/&gt;Running with Qt %3&lt;br/&gt;&lt;br/&gt;Copyright © &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;&lt;br/&gt;Projektversion: %1&lt;br/&gt;Gebaut mit Qt %2&lt;br/&gt;Läuft auf Qt %3&lt;br/&gt;&lt;br/&gt;Copyright © &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="obsolete">Schließen</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;&lt;br/&gt;Project version: %1&lt;br/&gt;Compiled with Qt %2&lt;br/&gt;Running with Qt %3&lt;br/&gt;&lt;br/&gt;Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;&lt;br/&gt;Projektversion: %1&lt;br/&gt;Gebaut mit Qt %2&lt;br/&gt;Läuft auf Qt %3&lt;br/&gt;&lt;br/&gt;Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <location filename="../AboutDialog.cpp" line="40"/>
        <source>A project for viewing Grand Theft Auto V Snapmatic&lt;br/&gt;
Pictures and Savegames</source>
        <translation>Ein Projekt zum ansehen von Grand Theft Auto V&lt;br/&gt;
Snapmatic Bilder und Spielständen</translation>
    </message>
    <message>
        <location filename="../AboutDialog.cpp" line="38"/>
        <source>A project for viewing and sync Grand Theft Auto V Snapmatic&lt;br/&gt;
Pictures and Savegames</source>
        <translation>Ein Projekt zum ansehen und synchronisieren von&lt;br/&gt;
Grand Theft Auto V Snapmatic Bilder und Spielständen</translation>
    </message>
</context>
<context>
    <name>CrewDatabase</name>
    <message>
        <location filename="../CrewDatabase.cpp" line="64"/>
        <source>No Crew</source>
        <translation>Keine Crew</translation>
    </message>
    <message>
        <source>Free</source>
        <comment>Crew Free (means no crew)</comment>
        <translatorcomment>Crew Keine (bedeutet keine Crew)</translatorcomment>
        <translation type="vanished">Keine</translation>
    </message>
</context>
<context>
    <name>ExportDialog</name>
    <message>
        <location filename="../ExportDialog.ui" line="14"/>
        <source>Dialog</source>
        <translation></translation>
    </message>
    <message>
        <source>Format</source>
        <translation type="obsolete">Format</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="51"/>
        <source>&amp;JPEG/PNG format</source>
        <translation>&amp;JPEG/PNG Format</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="58"/>
        <source>GTA &amp;Snapmatic format</source>
        <translation>GTA &amp;Snapmatic Format</translation>
    </message>
    <message>
        <source>Resolution</source>
        <translation type="obsolete">Auflösung</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="45"/>
        <source>Export Format</source>
        <translation>Export Format</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="68"/>
        <source>Export Size</source>
        <translation>Export Größe</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="74"/>
        <source>Default &amp;Size</source>
        <translation>&amp;Standard Größe</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="81"/>
        <source>&amp;Desktop Size</source>
        <translation>&amp;Desktop Größe</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="88"/>
        <source>&amp;Custom Size</source>
        <translation>&amp;Eigene Größe</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="100"/>
        <source>Custom Size:</source>
        <translation>Eigene Größe:</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="123"/>
        <source>x</source>
        <translation>x</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="198"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <location filename="../ExportDialog.ui" line="211"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
</context>
<context>
    <name>ImportDialog</name>
    <message>
        <location filename="../ImportDialog.ui" line="26"/>
        <source>Import...</source>
        <translation>Importieren...</translation>
    </message>
    <message>
        <location filename="../ImportDialog.ui" line="90"/>
        <source>Settings</source>
        <translation>Einstellungen</translation>
    </message>
    <message>
        <location filename="../ImportDialog.ui" line="96"/>
        <source>&amp;Keep Aspect Ratio</source>
        <translation>Seitenverhältnis &amp;behalten</translation>
    </message>
    <message>
        <location filename="../ImportDialog.ui" line="103"/>
        <source>&amp;Ignore Aspect Ratio</source>
        <translation>Seitenverhältnis &amp;ignorieren</translation>
    </message>
    <message>
        <location filename="../ImportDialog.ui" line="110"/>
        <source>&amp;Avatar</source>
        <translation>&amp;Avatar</translation>
    </message>
    <message>
        <location filename="../ImportDialog.ui" line="154"/>
        <source>&amp;OK</source>
        <translation>&amp;OK</translation>
    </message>
    <message>
        <location filename="../ImportDialog.ui" line="167"/>
        <source>&amp;Cancel</source>
        <translation>Abbre&amp;chen</translation>
    </message>
</context>
<context>
    <name>OptionsDialog</name>
    <message>
        <source>Options</source>
        <translation type="obsolete">Optionen</translation>
    </message>
    <message>
        <source>gta5sync - Options</source>
        <translation type="obsolete">gta5sync - Optionen</translation>
    </message>
    <message>
        <source>gta5sync - Settings</source>
        <translation type="vanished">gta5sync - Einstellungen</translation>
    </message>
    <message>
        <source>Profile</source>
        <translation type="vanished">Profil</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="33"/>
        <source>Content Open/Select Mode</source>
        <translation>Inhalte Öffnen/Auswählen Modus</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="39"/>
        <source>Open with Singleclick</source>
        <translation>Ein Klick zum öffnen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="49"/>
        <source>Open with Doubleclick</source>
        <translation>Doppelklick zum öffnen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="56"/>
        <source>Select with Singleclick</source>
        <translation>Ein Klick zum auswählen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="66"/>
        <source>Default Profile</source>
        <translation>Standardprofil</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="122"/>
        <source>Pictures</source>
        <translation>Bilder</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="128"/>
        <source>Export Size</source>
        <translation>Export Größe</translation>
    </message>
    <message>
        <source>Default Size: %1x%2</source>
        <translation type="obsolete">Standard Größe: %1x%2</translation>
    </message>
    <message>
        <source>Desktop Size: %1x%2</source>
        <translation type="obsolete">Desktop Größe: %1x%2</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="144"/>
        <source>Screen Resolution: %1x%2</source>
        <translation>Bildschirmauflösung: %1x%2</translation>
    </message>
    <message>
        <source>Custom Size</source>
        <translation type="obsolete">Eigene Größe</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="14"/>
        <source>%1 - Settings</source>
        <translation>%1 - Einstellungen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="27"/>
        <source>Profiles</source>
        <translation>Profile</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="78"/>
        <source>Custom GTA V Folder</source>
        <translation>Eigener GTA V Ordner</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="84"/>
        <source>Force using Custom Folder</source>
        <translation>Nutzung vom eigenen Ordner erzwingen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="96"/>
        <source>...</source>
        <translation>...</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="134"/>
        <source>Default: %1x%2</source>
        <translation>Standard: %1x%2</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="153"/>
        <location filename="../OptionsDialog.ui" line="163"/>
        <source>Custom Size:</source>
        <translation>Eigene Größe:</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="189"/>
        <source>x</source>
        <translation>x</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="229"/>
        <source>Ignore Aspect Ratio</source>
        <translation>Seitenverhältnis ignorieren</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="241"/>
        <source>Export Quality</source>
        <translation>Export Qualität</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="247"/>
        <source>Enable Custom Quality</source>
        <translation>Eigene Export Qualität benutzen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="259"/>
        <source>Quality:</source>
        <translation>Qualität:</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="288"/>
        <source>%1%</source>
        <translation>%1%</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="303"/>
        <source>Picture Viewer</source>
        <translation>Snapmatic Bildansicht</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="309"/>
        <source>Enable Navigation Bar</source>
        <translation>Aktiviere Navigationsleiste</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="333"/>
        <source>Players</source>
        <translation>Spieler</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="373"/>
        <source>ID</source>
        <translation>ID</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="378"/>
        <source>Name</source>
        <translation>Name</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="387"/>
        <location filename="../OptionsDialog.ui" line="393"/>
        <source>Language</source>
        <translation>Sprache</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="419"/>
        <source>Sync</source>
        <translation>Sync</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="425"/>
        <source>Sync is not implemented at current time</source>
        <translation>Sync wurde bisher nicht implementiert</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="463"/>
        <source>&amp;OK</source>
        <extracomment>OK, Cancel, Apply</extracomment>
        <translation>&amp;OK</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="476"/>
        <source>&amp;Cancel</source>
        <extracomment>OK, Cancel, Apply</extracomment>
        <translation>Abbre&amp;chen</translation>
    </message>
    <message>
        <source>%1 (%2 if available) [sys]</source>
        <comment>System like PC System = %1, System Language like Deutsch = %2</comment>
        <translation type="obsolete">%1 (%2 wenn verfügbar) [sys]</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="129"/>
        <source>System</source>
        <comment>System like PC System</comment>
        <translation>System</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="129"/>
        <source>%1 (%2 if available)</source>
        <comment>System like PC System = %1, System Language like Deutsch = %2</comment>
        <translation>%1 (%2 wenn verfügbar)</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="288"/>
        <location filename="../OptionsDialog.cpp" line="292"/>
        <source>%1</source>
        <comment>%1</comment>
        <translation>%1</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="288"/>
        <source>The new Custom Folder will initialize after you restart %1.</source>
        <translation>Der eigene Ordner wird initialisiert sobald du %1 neugestartet hast.</translation>
    </message>
    <message>
        <source>The new Custom Folder initialize after you restart %1.</source>
        <translation type="vanished">Der eigene Ordner initialisiert sobald du %1 neugestartet hast.</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="292"/>
        <source>The language change will take effect after you restart %1.</source>
        <translation>Die Änderung der Sprache nimmt Effekt sobald du %1 neugestartet hast.</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="302"/>
        <source>No Profile</source>
        <comment>No Profile, as default</comment>
        <translation>Kein Profil</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="310"/>
        <location filename="../OptionsDialog.cpp" line="314"/>
        <location filename="../OptionsDialog.cpp" line="316"/>
        <source>Profile: %1</source>
        <translation>Profil: %1</translation>
    </message>
</context>
<context>
    <name>PictureDialog</name>
    <message>
        <location filename="../PictureDialog.ui" line="14"/>
        <source>%1 - Snapmatic Picture Viewer</source>
        <translation>%1 - Snapmatic Bildansicht</translation>
    </message>
    <message>
        <source>&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</source>
        <translation type="obsolete">&lt;html&gt;&lt;head/&gt;&lt;body&gt;&lt;p&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br/&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5&lt;/p&gt;&lt;/body&gt;&lt;/html&gt;</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4 (Crew %5)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Created: &lt;/span&gt;%8&lt;br/&gt;</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4 (Crew %5)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Erstellt: &lt;/span&gt;%8</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="104"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4 (Crew %5)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Created: &lt;/span&gt;%8</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%7 (%1, %2, %3)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4 (Crew %5)&lt;br/&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Erstellt: &lt;/span&gt;%8</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="167"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="189"/>
        <source>&amp;Close</source>
        <translation>&amp;Schließen</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Picture Title: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Bildtitel: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="89"/>
        <location filename="../PictureExport.cpp" line="221"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <source>Copy</source>
        <translation type="obsolete">Kopieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="186"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="132"/>
        <source>Export as &amp;JPG picture...</source>
        <translation>Exportiere als &amp;JPG Bild...</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="133"/>
        <source>Export as &amp;GTA Snapmatic...</source>
        <translation>Exportiere als &amp;GTA Snapmatic...</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="347"/>
        <source>Key 1 - Avatar Preview Mode
Key 2 - Toggle Overlay
Arrow Keys - Navigate</source>
        <translation>Taste 1 - Avatar Vorschaumodus
Taste 2 - Overlay umschalten
Pfeiltasten - Navigieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="406"/>
        <location filename="../PictureDialog.cpp" line="478"/>
        <source>Snapmatic Picture Viewer</source>
        <translation>Snapmatic Bildansicht</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="406"/>
        <location filename="../PictureDialog.cpp" line="478"/>
        <source>Failed at %1</source>
        <translation>Fehlgeschlagen bei %1</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="533"/>
        <source>Avatar Preview Mode
Press 1 for Default View</source>
        <translation>Avatar Vorschaumodus
Drücke 1 für Standardmodus</translation>
    </message>
    <message>
        <source>1 - Avatar Preview Mode
2 - Toggle Overlay
Arrow Keys - Navigate</source>
        <comment>// L is for Left and R is for Right, Left Arrow Right Arrow</comment>
        <translation type="vanished">1 - Avatar Vorschaumodus
2 - Overlay umschalten
Pfeiltasten - Navigieren</translation>
    </message>
    <message>
        <source>1 - Avatar Preview Mode
2 - Toggle Overlay
L Arrow - Back
R Arrow - Next</source>
        <comment>L is for Left and R is for Right, Left Arrow Right Arrow</comment>
        <translation type="vanished">1 - Avatar Vorschaumodus
2 - Overlay umschalten
L Pfeil - Zurück
R Pfeil - Weiter</translation>
    </message>
    <message>
        <source>Avatar Preview Mode
Press A for Default View</source>
        <translation type="vanished">Avatar Vorschaumodus
Drücke A für Standardansicht</translation>
    </message>
    <message>
        <source>Avatar Preview Mode&lt;br&gt;Press A for Default View</source>
        <translation type="vanished">Avatar Vorschaumodus&lt;br&gt;Drücke A für Standardansicht</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="467"/>
        <location filename="../PictureDialog.cpp" line="477"/>
        <source>No player</source>
        <translation>Keine Spieler</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="470"/>
        <location filename="../PictureDialog.cpp" line="477"/>
        <source>No crew</source>
        <translation>Keine Crew</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="477"/>
        <source>Unknown Location</source>
        <translation>Unbekannter Standort</translation>
    </message>
    <message>
        <source>Export picture...</source>
        <translation type="obsolete">Exportiere Bild...</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="88"/>
        <source>Export as JPG picture...</source>
        <translation>Exportiere als JPG Bild...</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="92"/>
        <source>JPEG picture (*.jpg)</source>
        <translation>JPEG Bild (*.jpg)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="93"/>
        <source>Portable Network Graphics (*.png)</source>
        <translation>Portable Network Graphics (*.png)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="143"/>
        <location filename="../PictureExport.cpp" line="147"/>
        <location filename="../PictureExport.cpp" line="181"/>
        <location filename="../PictureExport.cpp" line="187"/>
        <source>Export as JPG picture</source>
        <translation>Exportiere als JPG Bild</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="143"/>
        <location filename="../PictureExport.cpp" line="246"/>
        <source>Overwrite %1 with current Snapmatic picture?</source>
        <translation>Überschreibe %1 mit aktuellen Snapmatic Bild?</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="246"/>
        <location filename="../PictureExport.cpp" line="250"/>
        <location filename="../PictureExport.cpp" line="265"/>
        <location filename="../PictureExport.cpp" line="286"/>
        <location filename="../PictureExport.cpp" line="291"/>
        <location filename="../PictureExport.cpp" line="297"/>
        <source>Export as GTA Snapmatic</source>
        <translation>Exportiere als GTA Snapmatic</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="147"/>
        <location filename="../PictureExport.cpp" line="250"/>
        <source>Failed to overwrite %1 with current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Überschreiben von %1 mit aktuellen Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="181"/>
        <location filename="../PictureExport.cpp" line="265"/>
        <location filename="../PictureExport.cpp" line="286"/>
        <source>Failed to export current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Exportieren vom aktuellen Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="291"/>
        <source>Exported Snapmatic to &quot;%1&quot; because of using the .auto extension.</source>
        <translation>Snapmatic wurde wegen Benutzung der .auto Erweiterung zu &quot;%1&quot; exportiert.</translation>
    </message>
    <message>
        <source>Exported Snapmatic to &quot;%1&quot; because of using the .auto extension</source>
        <translation type="vanished">Snapmatic wurde wegen Benutzung der .auto Erweiterung zu &quot;%1&quot; exportiert</translation>
    </message>
    <message>
        <source>Copy picture</source>
        <translation type="obsolete">Bild kopieren</translation>
    </message>
    <message>
        <source>Export picture for Import...</source>
        <translation type="obsolete">Exporti</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="220"/>
        <source>Export as GTA Snapmatic...</source>
        <translation>Exportiere als GTA Snapmatic...</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="224"/>
        <source>GTA V Export (*.g5e)</source>
        <translation>GTA V Export (*.g5e)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="225"/>
        <source>GTA V Raw Export (*.auto)</source>
        <translation>GTA V Roher Export (*.auto)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="226"/>
        <source>Snapmatic pictures (PGTA*)</source>
        <translation>Snapmatic Bilder (PGTA*)</translation>
    </message>
    <message>
        <source>All files (**)</source>
        <translation type="vanished">Alle Dateien (**)</translation>
    </message>
    <message>
        <source>Failed to copy current Snapmatic picture</source>
        <translation type="vanished">Fehlgeschlagen beim Kopieren vom Snapmatic Bild</translation>
    </message>
    <message>
        <source>Failed to save current picture</source>
        <translation type="obsolete">Fehlgeschlagen beim Speichern vom aktuellen Bild</translation>
    </message>
    <message>
        <source>JPEG picture (*.jpg);;Portable Network Graphics (*.png)</source>
        <translation type="obsolete">JPEG Bild (*.jpg);;Portable Network Graphics (*.png)</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="164"/>
        <source>Export picture</source>
        <translation>Bild exportieren</translation>
    </message>
    <message>
        <source>Snapmatic Picture Exporter</source>
        <translation type="obsolete">Snapmatic Bild Exporter</translation>
    </message>
    <message>
        <source>Failed to save the picture</source>
        <translation type="obsolete">Beim Speichern des Bildes ist ein Fehler aufgetreten</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="187"/>
        <location filename="../PictureExport.cpp" line="297"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
</context>
<context>
    <name>ProfileInterface</name>
    <message>
        <location filename="../ProfileInterface.ui" line="14"/>
        <source>Profile Interface</source>
        <translation>Profil Interface</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="55"/>
        <source>Loading file %1 of %2 files</source>
        <oldsource>Loading %1 files of %2 files</oldsource>
        <translation>Lade Datei %1 von %2 Dateien</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="166"/>
        <source>%1 %2</source>
        <translation>%1 %2</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="192"/>
        <source>Import exported file</source>
        <translation>Importiere exportierte Datei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="195"/>
        <source>&amp;Import...</source>
        <translation>&amp;Importieren...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="211"/>
        <source>Close profile</source>
        <translation>Profil schließen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="214"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>Import copy</source>
        <translation type="obsolete">Kopie importieren</translation>
    </message>
    <message>
        <source>Content of Profile %1</source>
        <translation type="obsolete">Inhalt vom Profil %1</translation>
    </message>
    <message>
        <source>View</source>
        <translation type="obsolete">Ansehen</translation>
    </message>
    <message>
        <source>Close Profile</source>
        <translation type="obsolete">Profil schließen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="108"/>
        <source>Loading...</source>
        <translation>Lade...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="384"/>
        <location filename="../ProfileInterface.cpp" line="421"/>
        <source>Import...</source>
        <translation>Importieren...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="385"/>
        <location filename="../ProfileInterface.cpp" line="475"/>
        <location filename="../ProfileInterface.cpp" line="480"/>
        <location filename="../ProfileInterface.cpp" line="507"/>
        <location filename="../ProfileInterface.cpp" line="523"/>
        <location filename="../ProfileInterface.cpp" line="673"/>
        <location filename="../ProfileInterface.cpp" line="678"/>
        <location filename="../ProfileInterface.cpp" line="696"/>
        <location filename="../ProfileInterface.cpp" line="701"/>
        <location filename="../ProfileInterface.cpp" line="712"/>
        <location filename="../ProfileInterface.cpp" line="749"/>
        <location filename="../ProfileInterface.cpp" line="755"/>
        <source>Import</source>
        <translation>Importieren</translation>
    </message>
    <message>
        <source>All profile files (SGTA* PGTA*)</source>
        <translation type="vanished">Alle Profildateien (SGTA* PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="388"/>
        <source>Importable files (*.g5e *.jpg *.png SGTA* PGTA*)</source>
        <translation>Importfähige Dateien (*.g5e *.jpg *.png SGTA* PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="390"/>
        <location filename="../UserInterface.cpp" line="344"/>
        <source>Savegames files (SGTA*)</source>
        <translation>Spielstanddateien (SGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="391"/>
        <location filename="../UserInterface.cpp" line="345"/>
        <source>Snapmatic pictures (PGTA*)</source>
        <translation>Snapmatic Bilder (PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="392"/>
        <source>All image files (*.jpg *.png)</source>
        <translation>Alle Bilddateien (*.jpg *.png)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="393"/>
        <location filename="../UserInterface.cpp" line="346"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="422"/>
        <location filename="../ProfileInterface.cpp" line="437"/>
        <source>Import file %1 of %2 files</source>
        <translation>Importiere Datei %1 von %2 Dateien</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="475"/>
        <source>Import failed with...

%1</source>
        <translation>Importieren fehlgeschlagen mit...

%1</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="507"/>
        <location filename="../UserInterface.cpp" line="386"/>
        <source>Failed to read Snapmatic picture</source>
        <translation>Fehler beim Lesen vom Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="523"/>
        <location filename="../UserInterface.cpp" line="402"/>
        <source>Failed to read Savegame file</source>
        <translation>Fehler beim Lesen von Spielstanddatei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="673"/>
        <source>Can&apos;t import %1 because of not valid file format</source>
        <translation>Kann %1 nicht importieren weil das Dateiformat nicht gültig ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="696"/>
        <source>Failed to import the Snapmatic picture, file not begin with PGTA or end with .g5e</source>
        <translation>Fehlgeschlagen beim Importieren vom Snapmatic Bild, Datei beginnt nicht mit PGTA oder endet mit .g5e</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="701"/>
        <source>Failed to import the Snapmatic picture, the picture is already in the game</source>
        <translation>Fehlgeschlagen beim Importieren vom Snapmatic Bild, dieses Bild ist bereits im Spiel</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="856"/>
        <source>%1Export Snapmatic pictures%2&lt;br&gt;&lt;br&gt;JPG pictures make it possible to open the picture with a Image Viewer&lt;br&gt;GTA Snapmatic make it possible to import the picture into the game&lt;br&gt;&lt;br&gt;Export as:</source>
        <translation>%1Exportiere Snapmatic Bilder%2&lt;br&gt;&lt;br&gt;JPG Bilder machen es möglich sie mit ein Bildansicht Programm zu öffnen&lt;br&gt;Das GTA Snapmatic Format macht es möglich sie wieder ins Game zu importieren&lt;br&gt;&lt;br&gt;Exportieren als:</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="480"/>
        <location filename="../ProfileInterface.cpp" line="678"/>
        <location filename="../UserInterface.cpp" line="434"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="61"/>
        <source>Enabled pictures: %1 of %2</source>
        <translation>Aktivierte Bilder: %1 von %2</translation>
    </message>
    <message>
        <source>Failed to import the Snapmatic picture, file not begin with PGTA</source>
        <translation type="vanished">Fehlgeschlagen beim Importieren vom Snapmatic Bild, Datei beginnt nicht mit PGTA</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="712"/>
        <source>Failed to import the Snapmatic picture, can&apos;t copy the file into profile</source>
        <translation>Fehlgeschlagen beim Importieren vom Snapmatic Bild, kann Snapmatic Bild nicht ins Profil kopieren </translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="749"/>
        <source>Failed to import the Savegame, can&apos;t copy the file into profile</source>
        <translation>Fehlgeschlagen beim Importieren vom Spielstand, kann Spielstanddatei nicht ins Profil kopieren</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="755"/>
        <source>Failed to import the Savegame, no Savegame slot is left</source>
        <translation>Fehlgeschlagen beim Importieren vom Spielstand, kein Spielstandslot mehr frei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="841"/>
        <location filename="../ProfileInterface.cpp" line="859"/>
        <source>JPG pictures and GTA Snapmatic</source>
        <translation>JPG Bilder und GTA Snapmatic</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="842"/>
        <location filename="../ProfileInterface.cpp" line="864"/>
        <source>JPG pictures only</source>
        <translation>Nur JPG Bilder</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="843"/>
        <location filename="../ProfileInterface.cpp" line="868"/>
        <source>GTA Snapmatic only</source>
        <translation>Nur GTA Snapmatic</translation>
    </message>
    <message>
        <source>Export Snapmatic pictures

JPG pictures make it possible to open the picture with a Image Viewer
GTA Snapmatic make it possible to import the picture into the game

Export as:</source>
        <translation type="obsolete">Exportiere Snapmatic Bilder

JPG Bilder machen es möglich sie mit ein Bildansicht Programm zu öffnen
Das GTA Snapmatic Format macht es möglich sie wieder ins Game zu importieren

Exportieren als:</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="953"/>
        <location filename="../ProfileInterface.cpp" line="995"/>
        <source>No Snapmatic pictures or Savegames files are selected</source>
        <translation>Keine Snapmatic Bilder oder Spielstände ausgewählt</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="961"/>
        <location filename="../ProfileInterface.cpp" line="989"/>
        <location filename="../ProfileInterface.cpp" line="995"/>
        <source>Remove selected</source>
        <translation>Auswahl löschen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="961"/>
        <source>You really want remove the selected Snapmatic picutres and Savegame files?</source>
        <translation>Möchtest du wirklich die ausgewählten Snapmatic Bilder und Spielstanddateien löschen?</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="989"/>
        <source>Failed at remove the complete selected Snapmatic pictures and/or Savegame files</source>
        <translation>Fehlgeschlagen beim kompletten entfernen der ausgewählten Snapmatic Bilder und/oder der Spielstanddateien</translation>
    </message>
    <message>
        <source>Failed to import copy of Snapmatic picture because the file not begin with PGTA</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Snapmatic Bild weil die Datei nicht mit PGTA begint </translation>
    </message>
    <message>
        <source>Failed to import copy of Snapmatic picture because the copy failed</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Snapmatic Bild weil kopieren fehlgeschlagen ist</translation>
    </message>
    <message>
        <source>Failed to import copy of Savegame file because the copy failed</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Spielstand weil kopieren fehlgeschlagen ist</translation>
    </message>
    <message>
        <source>Failed to import copy of Savegame file because no free Savegame slot left</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Spielstand weil kein Spielstandslot mehr übrig ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="818"/>
        <location filename="../ProfileInterface.cpp" line="856"/>
        <location filename="../ProfileInterface.cpp" line="933"/>
        <location filename="../ProfileInterface.cpp" line="953"/>
        <source>Export selected</source>
        <translation>Auswahl exportieren</translation>
    </message>
    <message>
        <source>Export and Copy pictures</source>
        <translation type="obsolete">Bilder exportieren und kopieren</translation>
    </message>
    <message>
        <source>Export pictures</source>
        <translation type="obsolete">Bilder exportieren</translation>
    </message>
    <message>
        <source>Copy pictures</source>
        <translation type="obsolete">Bilder kopieren</translation>
    </message>
    <message>
        <source>How should we deal with the Snapmatic pictures?</source>
        <translation type="obsolete">Wie sollen wir mit den Snapmatic Bilder umgehen?</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="899"/>
        <source>Export selected...</source>
        <translation>Auswahl exportieren...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="900"/>
        <source>Initializing export...</source>
        <translation>Initialisiere Export...</translation>
    </message>
    <message>
        <source>Initializing...</source>
        <translation type="obsolete">Initialisierung...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="933"/>
        <source>Export failed with...

%1</source>
        <translation>Exportieren fehlgeschlagen bei...\n%1</translation>
    </message>
    <message>
        <source>Delete selected</source>
        <translation type="obsolete">Auswahl löschen</translation>
    </message>
    <message>
        <source>You really want delete the selected content?</source>
        <translation type="obsolete">Möchtest du wirklich den ausgewählten Inhalt löschen?</translation>
    </message>
    <message>
        <source>Failed at delete all selected content</source>
        <translation type="obsolete">Fehlgeschlagen beim Löschen von alle ausgewählte Inhalte</translation>
    </message>
    <message>
        <source>Current export job: %1</source>
        <translation type="obsolete">Aktueller Exportiervorgang: %1</translation>
    </message>
    <message>
        <location filename="../ExportThread.cpp" line="96"/>
        <location filename="../ExportThread.cpp" line="135"/>
        <location filename="../ExportThread.cpp" line="156"/>
        <source>Export file %1 of %2 files</source>
        <translation>Exportiere Datei %1 von %2 Dateien</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="342"/>
        <source>All profile files (*.g5e SGTA* PGTA*)</source>
        <translation>Alle Profildateien (*.g5e SGTA* PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="389"/>
        <location filename="../UserInterface.cpp" line="343"/>
        <source>GTA V Export (*.g5e)</source>
        <translation>GTA V Export (*.g5e)</translation>
    </message>
</context>
<context>
    <name>QApplication</name>
    <message>
        <location filename="../main.cpp" line="68"/>
        <source>Font</source>
        <translation>Schrift</translation>
    </message>
    <message>
        <location filename="../main.cpp" line="68"/>
        <source>Selected Font: %1</source>
        <translation>Ausgewähle Schrift: %1</translation>
    </message>
</context>
<context>
    <name>SavegameDialog</name>
    <message>
        <location filename="../SavegameDialog.ui" line="14"/>
        <location filename="../SavegameDialog.cpp" line="33"/>
        <source>Savegame Viewer</source>
        <translation>Spielstandanzeiger</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="29"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Savegame&lt;/span&gt;&lt;br&gt;&lt;br&gt;%1</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;Spielstand&lt;/span&gt;&lt;br&gt;&lt;br&gt;%1</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="63"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <source>Cop&amp;y</source>
        <translation type="obsolete">&amp;Kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="76"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>Copy</source>
        <translation type="obsolete">Kopieren</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="obsolete">Schließen</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.cpp" line="33"/>
        <source>Failed at %1</source>
        <translation>Fehlgeschlagen bei %1</translation>
    </message>
</context>
<context>
    <name>SavegameWidget</name>
    <message>
        <location filename="../SavegameWidget.ui" line="14"/>
        <source>Savegame Widget</source>
        <translation>Spielstand Widget</translation>
    </message>
    <message>
        <source>The Third Way (100%) - 00/00/00 00:00:00</source>
        <translation type="vanished">The Third Way (100%) - 00/00/00 00:00:00</translation>
    </message>
    <message>
        <source>Savegame %1
%2</source>
        <translation type="vanished">Spielstand %1
%2</translation>
    </message>
    <message>
        <source>SAVE - %1&lt;br&gt;%2</source>
        <translation type="vanished">SPIELSTAND - %1&lt;br&gt;%2</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="86"/>
        <source>View</source>
        <translation>Ansehen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="102"/>
        <location filename="../SavegameCopy.cpp" line="48"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <source>Copy</source>
        <translation type="obsolete">Kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="121"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="118"/>
        <location filename="../SavegameWidget.cpp" line="131"/>
        <location filename="../SavegameWidget.cpp" line="144"/>
        <source>Delete savegame</source>
        <translation>Savegame löschen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="49"/>
        <source>Export Savegame...</source>
        <translation>Spielstand exportieren...</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="67"/>
        <source>SAVE %3 - %1&lt;br&gt;%2</source>
        <translation>SPIELSTAND %3 - %1&lt;br&gt;%2</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="93"/>
        <location filename="../SavegameWidget.cpp" line="94"/>
        <source>WRONG FORMAT</source>
        <translation>FALSCHES FORMAT</translation>
    </message>
    <message>
        <source>AUTO</source>
        <translation type="vanished">AUTO</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="56"/>
        <source>AUTOSAVE - %1
%2</source>
        <translation>AUTOSAVE - %1
%2</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="57"/>
        <source>SAVE %3 - %1
%2</source>
        <translation>SPIELSTAND %3 - %1
%2</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="117"/>
        <source>UNKNOWN</source>
        <translation>UNKNOWN</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="131"/>
        <source>Are you sure to delete %1 from your savegames?</source>
        <translation>Bist du sicher %1 von deinen Spielständen zu löschen?</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="144"/>
        <source>Failed at deleting %1 from your savegames</source>
        <translation>Fehlgeschlagen beim Löschen %1 von deinen Spielständen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1118"/>
        <source>&amp;View</source>
        <translation>A&amp;nsehen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1120"/>
        <source>&amp;Remove</source>
        <translation>Entfe&amp;rnen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1124"/>
        <location filename="../ProfileInterface.cpp" line="1135"/>
        <source>&amp;Select</source>
        <translation>Au&amp;swählen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1125"/>
        <source>&amp;Deselect</source>
        <translation>A&amp;bwählen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1126"/>
        <location filename="../ProfileInterface.cpp" line="1136"/>
        <source>Select &amp;All</source>
        <translation>&amp;Alles auswählen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1129"/>
        <source>&amp;Deselect All</source>
        <translation>Alles a&amp;bwählen</translation>
    </message>
    <message>
        <source>Select</source>
        <translation type="obsolete">Auswählen</translation>
    </message>
    <message>
        <source>Deselect</source>
        <translation type="obsolete">Abwählen</translation>
    </message>
    <message>
        <source>Select all</source>
        <translation type="obsolete">Alles auswählen</translation>
    </message>
    <message>
        <source>Ctrl+S</source>
        <translation type="obsolete">Strg+S</translation>
    </message>
    <message>
        <source>Deselect all</source>
        <translation type="obsolete">Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="83"/>
        <source>View savegame</source>
        <translation>Spielstand ansehen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="99"/>
        <source>Copy savegame</source>
        <translation>Spielstand kopieren</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1119"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="51"/>
        <source>Savegame files (SGTA*)</source>
        <translation>Spielstanddateien (SGTA*)</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="52"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="70"/>
        <location filename="../SavegameCopy.cpp" line="74"/>
        <location filename="../SavegameCopy.cpp" line="87"/>
        <location filename="../SavegameCopy.cpp" line="93"/>
        <source>Export Savegame</source>
        <translation>Spielstand exportieren</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="70"/>
        <source>Overwrite %1 with current Savegame?</source>
        <translation>Überschreibe %1 mit aktuellen Spielstand?</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="74"/>
        <source>Failed to overwrite %1 with current Savegame</source>
        <translation>Fehlgeschlagen beim Überschrieben von %1 mit aktuellen Spielstand</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="87"/>
        <source>Failed to export current Savegame</source>
        <translation>Fehlgeschlagen beim Exportieren vom aktuellen Spielstand</translation>
    </message>
    <message>
        <source>Failed to copy current Savegame</source>
        <translation type="obsolete">Fehlgeschlagen beim Kopieren vom aktuellen Spielstand</translation>
    </message>
    <message>
        <source>Overwrite %1 with current savegame?</source>
        <translation type="obsolete">Überschreibe %1 mit aktuellen Spielstand?</translation>
    </message>
    <message>
        <source>Failed to overwrite %1 with current savegame</source>
        <translation type="obsolete">Fehlgeschlagen beim Überschreiben von %1 mit aktuellen Spielstand </translation>
    </message>
    <message>
        <source>Failed to copy current savegame</source>
        <translation type="obsolete">Fehlgeschlagen beim Kopieren vom Spielstand</translation>
    </message>
    <message>
        <source>Failed to copy the savegame</source>
        <translation type="obsolete">Beim Kopieren vom Spielstand ist ein Fehler aufgetreten</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="93"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
    <message>
        <source>Are you sure to delete %1 from your Savegames?</source>
        <translation type="obsolete">Bist du sicher %1 von deinen Spielständen zu löschen?</translation>
    </message>
    <message>
        <source>Failed at deleting %1 from your Savegames</source>
        <translation type="obsolete">Fehlgeschlagen beim Löschen %1 von deinen Spielständen</translation>
    </message>
</context>
<context>
    <name>SnapmaticEditor</name>
    <message>
        <location filename="../SnapmaticEditor.ui" line="14"/>
        <location filename="../SnapmaticEditor.ui" line="81"/>
        <location filename="../SnapmaticEditor.cpp" line="239"/>
        <source>Snapmatic Properties</source>
        <translation>Snapmatic Eigenschaften</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="44"/>
        <source>Snapmatic Type</source>
        <translation>Snapmatic Typ</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="50"/>
        <source>Editor</source>
        <translation>Editor</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="57"/>
        <source>Selfie</source>
        <translation>Selbstporträt</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="64"/>
        <source>Regular</source>
        <translation>Typisch</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="71"/>
        <source>Mugshot</source>
        <translation>Fahndungsfoto</translation>
    </message>
    <message>
        <source>Custom</source>
        <translation type="vanished">Eigenes</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="94"/>
        <source>Director</source>
        <translation>Director</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="87"/>
        <source>Meme</source>
        <translation>Meme</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="289"/>
        <source>Snapmatic Title</source>
        <translation>Snapmatic Titel</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="104"/>
        <source>Snapmatic Values</source>
        <translation>Snapmatic Werte</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="113"/>
        <location filename="../SnapmaticEditor.cpp" line="194"/>
        <source>Crew: %1 (%2)</source>
        <translation>Crew: %1 (%2)</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="126"/>
        <location filename="../SnapmaticEditor.cpp" line="179"/>
        <source>Title: %1 (%2)</source>
        <translation>Titel: %1 (%2)</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="136"/>
        <location filename="../SnapmaticEditor.cpp" line="183"/>
        <location filename="../SnapmaticEditor.cpp" line="187"/>
        <source>Appropriate: %1</source>
        <translation>Angemessen: %1</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="149"/>
        <source>Extras</source>
        <translation>Extras</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="155"/>
        <source>Qualify as Avatar automatically at apply</source>
        <translation>Beim Übernehmen als Avatar qualifizieren  </translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="168"/>
        <source>Qualify as Avatar allows you to use this Snapmatic as a Social Club profile picture</source>
        <translation>Das Qualifizieren als Avatar erlaubt dir dieses Snapmatic als Social Club Profilbild zu nutzen</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="218"/>
        <source>&amp;Apply</source>
        <translation>&amp;Übernehmen</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.ui" line="231"/>
        <source>&amp;Cancel</source>
        <translation>Abbre&amp;chen</translation>
    </message>
    <message>
        <source>Apply</source>
        <translation type="vanished">Übernehmen</translation>
    </message>
    <message>
        <source>Cancel</source>
        <translation type="vanished">Cancel</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="178"/>
        <location filename="../SnapmaticEditor.cpp" line="193"/>
        <source>Edit</source>
        <translation>Bearbeiten</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="183"/>
        <source>Yes</source>
        <comment>Yes, should work fine</comment>
        <translation>Ja</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="187"/>
        <source>No</source>
        <comment>No, could lead to issues</comment>
        <translation>Nein</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="239"/>
        <source>Patching of Snapmatic Properties failed because of I/O Error</source>
        <translation>Patchen von Snapmatic Eigenschaften fehlgeschlagen wegen I/O Fehler</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="289"/>
        <source>New Snapmatic title:</source>
        <translation>Neuer Snapmatic Titel:</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="314"/>
        <source>Snapmatic Crew</source>
        <translation>Snapmatic Crew</translation>
    </message>
    <message>
        <location filename="../SnapmaticEditor.cpp" line="314"/>
        <source>New Snapmatic crew:</source>
        <translation>Neue Snapmatic Crew:</translation>
    </message>
</context>
<context>
    <name>SnapmaticPicture</name>
    <message>
        <location filename="../SnapmaticPicture.cpp" line="363"/>
        <source>PHOTO - %1</source>
        <translation>FOTO - %1</translation>
    </message>
</context>
<context>
    <name>SnapmaticWidget</name>
    <message>
        <location filename="../SnapmaticWidget.ui" line="14"/>
        <source>Snapmatic Widget</source>
        <translation>Snapmatic Widget</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="82"/>
        <source>PHOTO - 00/00/00 00:00:00</source>
        <translation>FOTO - 00/00/00 00:00:00</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="101"/>
        <source>View</source>
        <translation>Ansehen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="120"/>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="136"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="152"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="149"/>
        <location filename="../SnapmaticWidget.cpp" line="159"/>
        <location filename="../SnapmaticWidget.cpp" line="168"/>
        <source>Delete picture</source>
        <translation>Bild löschen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="159"/>
        <source>Are you sure to delete %1 from your Snapmatic pictures?</source>
        <translation>Bist du sicher %1 von deinen Snapmatic Bilder zu löschen?</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1077"/>
        <source>Edi&amp;t</source>
        <translation>Bearbei&amp;ten</translation>
    </message>
    <message>
        <source>Enable &amp;In-game</source>
        <translation type="vanished">&amp;Im Spiel aktivieren</translation>
    </message>
    <message>
        <source>Disable &amp;In-game</source>
        <translation type="vanished">&amp;Im Spiel deaktivieren</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1087"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <source>Export as &amp;JPG picture</source>
        <translation type="obsolete">Exportiere als &amp;JPG Bild</translation>
    </message>
    <message>
        <source>Export as &amp;GTA Snapmatic</source>
        <translation type="obsolete">Exportiere als &amp;GTA Snapmatic</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1080"/>
        <source>Show &amp;In-game</source>
        <translation>&amp;Im Spiel anzeigen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1084"/>
        <source>Hide &amp;In-game</source>
        <translation>&amp;Im Spiel ausblenden</translation>
    </message>
    <message>
        <source>&amp;Edit Properties</source>
        <translation type="vanished">&amp;Eigenschaften bearbeiten</translation>
    </message>
    <message>
        <source>PHOTO - %1</source>
        <translation type="vanished">FOTO - %1</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1086"/>
        <source>&amp;Edit Properties...</source>
        <translation>&amp;Eigenschaften bearbeiten...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1088"/>
        <source>Export as &amp;JPG picture...</source>
        <translation>Exportiere als &amp;JPG Bild...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1089"/>
        <source>Export as &amp;GTA Snapmatic...</source>
        <translation>Exportiere als &amp;GTA Snapmatic...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1090"/>
        <source>&amp;View</source>
        <translation>A&amp;nsehen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1093"/>
        <source>&amp;Remove</source>
        <translation>Entfe&amp;rnen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1097"/>
        <location filename="../ProfileInterface.cpp" line="1108"/>
        <source>&amp;Select</source>
        <translation>Au&amp;swählen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1098"/>
        <source>&amp;Deselect</source>
        <translation>A&amp;bwählen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1099"/>
        <location filename="../ProfileInterface.cpp" line="1109"/>
        <source>Select &amp;All</source>
        <translation>Alles &amp;auswählen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="1102"/>
        <source>&amp;Deselect All</source>
        <translation>Alles a&amp;bwählen</translation>
    </message>
    <message>
        <source>Select</source>
        <translation type="obsolete">Auswählen</translation>
    </message>
    <message>
        <source>Deselect</source>
        <translation type="obsolete">Abwählen</translation>
    </message>
    <message>
        <source>Select all</source>
        <translation type="obsolete">Alles auswählen</translation>
    </message>
    <message>
        <source>Ctrl+S</source>
        <translation type="obsolete">Strg+S</translation>
    </message>
    <message>
        <source>Deselect all</source>
        <translation type="obsolete">Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="98"/>
        <source>View picture</source>
        <translation>Bild ansehen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="117"/>
        <source>Copy picture</source>
        <translation>Bild kopieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="133"/>
        <source>Export picture</source>
        <translation>Bild exportieren</translation>
    </message>
    <message>
        <source>You&apos;re sure to delete %1 from your Snapmatic pictures?</source>
        <translation type="obsolete">Bist du sicher %1 von deinen Snapmatic Bilder zu löschen?</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="168"/>
        <source>Failed at deleting %1 from your Snapmatic pictures</source>
        <translation>Fehlgeschlagen beim Löschen %1 von deinen Snapmatic Bildern</translation>
    </message>
</context>
<context>
    <name>UserInterface</name>
    <message>
        <source>Grand Theft Auto V Sync</source>
        <translation type="obsolete">Grand Theft Auto V Sync</translation>
    </message>
    <message>
        <source>GTA V Sync</source>
        <translation type="obsolete">GTA V Sync</translation>
    </message>
    <message>
        <source>gta5sync - %1</source>
        <translation type="vanished">gta5sync - %1</translation>
    </message>
    <message>
        <source>File</source>
        <translation type="obsolete">Datei</translation>
    </message>
    <message>
        <source>Help</source>
        <translation type="obsolete">Hilfe</translation>
    </message>
    <message>
        <source>Edit</source>
        <translation type="obsolete">Bearbeiten</translation>
    </message>
    <message>
        <source>Profile</source>
        <translation type="obsolete">Profil</translation>
    </message>
    <message>
        <source>About gta5sync</source>
        <translation type="obsolete">Über gta5sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="258"/>
        <source>Ctrl+A</source>
        <translation>Strg+A</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="obsolete">Schließen</translation>
    </message>
    <message>
        <source>Options</source>
        <translation type="obsolete">Optionen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="298"/>
        <source>Ctrl+O</source>
        <translation>Strg+O</translation>
    </message>
    <message>
        <source>Select all</source>
        <translation type="obsolete">Alles auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="250"/>
        <source>Ctrl+S</source>
        <translation>Strg+S</translation>
    </message>
    <message>
        <source>Deselect all</source>
        <translation type="obsolete">Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <source>Export selected</source>
        <translation type="obsolete">Auswahl exportieren</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="274"/>
        <source>Ctrl+E</source>
        <translation>Strg+E</translation>
    </message>
    <message>
        <source>Delete selected</source>
        <translation type="obsolete">Auswahl löschen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="266"/>
        <source>Ctrl+D</source>
        <translation>Strg+D</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="231"/>
        <source>Exit</source>
        <translation>Beenden</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="199"/>
        <source>&amp;Selection visibility</source>
        <translation>Auswahl &amp;Sichtbarkeit</translation>
    </message>
    <message>
        <source>&amp;About Product</source>
        <translation type="vanished">&amp;Über Produkt</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="228"/>
        <source>&amp;Exit</source>
        <translation>B&amp;eenden</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="234"/>
        <source>Ctrl+Q</source>
        <translation>Strg+Q</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="74"/>
        <source>Select profile</source>
        <translation>Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="105"/>
        <source>%1 %2</source>
        <translation>%1 %2</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="173"/>
        <source>&amp;File</source>
        <translation>&amp;Datei</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="183"/>
        <source>&amp;Help</source>
        <translation>&amp;Hilfe</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="189"/>
        <source>&amp;Edit</source>
        <translation>Bearb&amp;eiten</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="195"/>
        <source>&amp;Profile</source>
        <translation>&amp;Profil</translation>
    </message>
    <message>
        <source>Selection visibility</source>
        <translation type="vanished">Auswahl Sichtbarkeit</translation>
    </message>
    <message>
        <source>&amp;About gta5sync</source>
        <translation type="vanished">&amp;Über gta5sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="239"/>
        <source>Close &amp;Profile</source>
        <translation>&amp;Profil schließen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="242"/>
        <source>Ctrl+End</source>
        <translation>Strg+Ende</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="282"/>
        <source>Ctrl+Del</source>
        <translation>Strg+Entf</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="295"/>
        <source>&amp;Open File...</source>
        <translation>Datei &amp;öffnen...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="303"/>
        <location filename="../UserInterface.cpp" line="144"/>
        <source>Select &amp;GTA V Folder...</source>
        <translation>Wähle &amp;GTA V Ordner...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="309"/>
        <source>Ctrl+G</source>
        <translation>Strg+G</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="314"/>
        <source>Show In-gam&amp;e</source>
        <translation>Im Spiel anzeig&amp;en</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="322"/>
        <source>Hi&amp;de In-game</source>
        <translation>Im Spiel ausblen&amp;den</translation>
    </message>
    <message>
        <source>Hid&amp;e In-game</source>
        <translation type="vanished">Im Spiel ausblen&amp;den</translation>
    </message>
    <message>
        <source>&amp;Enable In-game</source>
        <translation type="vanished">Im Spiel aktivier&amp;en</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="317"/>
        <source>Shift+E</source>
        <translation>Umschalt+E</translation>
    </message>
    <message>
        <source>&amp;Disable In-game</source>
        <translation type="vanished">Im Spiel &amp;deaktivieren</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="325"/>
        <source>Shift+D</source>
        <translation>Umschalt+D</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="147"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>Select &amp;Profile</source>
        <translation type="obsolete">&amp;Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="223"/>
        <source>Ctrl+P</source>
        <translation>Strg+P</translation>
    </message>
    <message>
        <source>&amp;Options</source>
        <translation type="obsolete">&amp;Optionen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="247"/>
        <source>&amp;Settings</source>
        <translation>Ein&amp;stellungen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="255"/>
        <source>Select &amp;All</source>
        <translation>&amp;Alles auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="263"/>
        <source>&amp;Deselect All</source>
        <translation>Alles a&amp;bwählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="271"/>
        <source>&amp;Export selected...</source>
        <translation>Auswahl &amp;exportieren...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="279"/>
        <source>&amp;Remove selected</source>
        <translation>Auswahl entfe&amp;rnen</translation>
    </message>
    <message>
        <source>Ctrl+R</source>
        <translation type="obsolete">Strg+R</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="287"/>
        <source>&amp;Import files...</source>
        <translation>Dateien &amp;importieren...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="290"/>
        <source>Ctrl+I</source>
        <translation>Strg+I</translation>
    </message>
    <message>
        <source>GTA V Folder not found!</source>
        <translation type="obsolete">GTA V Ordner nicht gefunden!</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="62"/>
        <location filename="../UserInterface.cpp" line="213"/>
        <source>Select Profile</source>
        <translation>Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="306"/>
        <location filename="../OptionsDialog.cpp" line="448"/>
        <location filename="../UserInterface.cpp" line="93"/>
        <location filename="../UserInterface.cpp" line="488"/>
        <source>Select GTA V Folder...</source>
        <translation>Wähle GTA V Ordner...</translation>
    </message>
    <message>
        <source>Select GTA V &amp;Folder...</source>
        <translation type="vanished">Wähle GTA V &amp;Ordner...</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="339"/>
        <source>Open File...</source>
        <translation>Datei öffnen...</translation>
    </message>
    <message>
        <source>Import</source>
        <translation type="obsolete">Importieren</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="20"/>
        <location filename="../UserInterface.cpp" line="60"/>
        <source>%2 - %1</source>
        <translation>%2 - %1</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="220"/>
        <location filename="../UserInterface.cpp" line="59"/>
        <source>&amp;About %1</source>
        <translation>&amp;Über %1</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="386"/>
        <location filename="../UserInterface.cpp" line="402"/>
        <location filename="../UserInterface.cpp" line="429"/>
        <location filename="../UserInterface.cpp" line="434"/>
        <source>Open File</source>
        <translation>Datei öffnen</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="429"/>
        <source>Can&apos;t open %1 because of not valid file format</source>
        <translation>Kann nicht %1 öffnen weil Dateiformat nicht gültig ist</translation>
    </message>
    <message>
        <source>Change GTA V &amp;Folder</source>
        <translation type="obsolete">GTA V &amp;Ordner ändern</translation>
    </message>
    <message>
        <source>gta5sync</source>
        <translation type="obsolete">gta5sync</translation>
    </message>
    <message>
        <source>Grand Theft Auto V Folder not found!</source>
        <translation type="obsolete">Grand Theft Auto V Ordner wurde nicht gefunden!</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="131"/>
        <source>&amp;Reload</source>
        <translation>&amp;Neuladen</translation>
    </message>
    <message>
        <source>Reload</source>
        <translation type="obsolete">Neuladen</translation>
    </message>
    <message>
        <source>Reload profiles</source>
        <translation type="obsolete">Profile neuladen</translation>
    </message>
    <message>
        <source>Not able to reload profiles</source>
        <translation type="obsolete">Nicht fähig Profile neuzuladen</translation>
    </message>
</context>
</TS>
