<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="de_DE">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="../AboutDialog.ui" line="14"/>
        <source>About gta5sync</source>
        <translation>Über gta5sync</translation>
    </message>
    <message>
        <source>generated by class</source>
        <translation type="obsolete">Generiert von der Klasse</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;&lt;br/&gt;Project version: %1&lt;br/&gt;Compiled with Qt %2&lt;br/&gt;Running with Qt %3&lt;br/&gt;&lt;br/&gt;Copyright © &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;&lt;br/&gt;Projektversion: %1&lt;br/&gt;Gebaut mit Qt %2&lt;br/&gt;Läuft auf Qt %3&lt;br/&gt;&lt;br/&gt;Copyright © &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="104"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="59"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;&lt;br/&gt;Project version: %1&lt;br/&gt;Compiled with Qt %2&lt;br/&gt;Running with Qt %3&lt;br/&gt;&lt;br/&gt;Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;&lt;br/&gt;Projektversion: %1&lt;br/&gt;Gebaut mit Qt %2&lt;br/&gt;Läuft auf Qt %3&lt;br/&gt;&lt;br/&gt;Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
</context>
<context>
    <name>PictureDialog</name>
    <message>
        <location filename="../PictureDialog.ui" line="14"/>
        <source>%1 - Snapmatic Picture Viewer</source>
        <translation>%1 - Snapmatic Bildansicht</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Picture Title: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Bildtitel: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="78"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="94"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="101"/>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="108"/>
        <location filename="../PictureDialog.ui" line="111"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="71"/>
        <location filename="../PictureDialog.cpp" line="119"/>
        <source>Snapmatic Picture Viewer</source>
        <translation>Snapmatic Bildansicht</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="71"/>
        <location filename="../PictureDialog.cpp" line="119"/>
        <source>Failed at %1</source>
        <translation>Fehlgeschlagen bei %1</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="108"/>
        <location filename="../PictureDialog.cpp" line="118"/>
        <source>No player</source>
        <translation>Keine Spieler</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="111"/>
        <location filename="../PictureDialog.cpp" line="118"/>
        <source>No crew</source>
        <translation>Keine Crew</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="48"/>
        <source>JPEG picture (*.jpg)</source>
        <translation>JPEG Bild (*.jpg)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="49"/>
        <source>Portable Network Graphics (*.png)</source>
        <translation>Portable Network Graphics (*.png)</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="68"/>
        <location filename="../PictureExport.cpp" line="127"/>
        <source>Overwrite %1 with current Snapmatic picture?</source>
        <translation>Überschreibe %1 mit aktuellen Snapmatic Bild?</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="72"/>
        <location filename="../PictureExport.cpp" line="131"/>
        <source>Failed to overwrite %1 with current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Überschreiben von %1 mit aktuellen Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="145"/>
        <source>Failed to export current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Exportieren vom aktuellen Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="46"/>
        <location filename="../PictureCopy.cpp" line="68"/>
        <location filename="../PictureCopy.cpp" line="72"/>
        <location filename="../PictureCopy.cpp" line="85"/>
        <location filename="../PictureCopy.cpp" line="91"/>
        <source>Copy picture</source>
        <translation>Bild kopieren</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="49"/>
        <source>Snapmatic pictures (PGTA*)</source>
        <translation>Snapmatic Bilder (PGTA*)</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="50"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="85"/>
        <source>Failed to copy current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Kopieren vom Snapmatic Bild</translation>
    </message>
    <message>
        <source>Failed to save current picture</source>
        <translation type="obsolete">Fehlgeschlagen beim Speichern vom aktuellen Bild</translation>
    </message>
    <message>
        <source>JPEG picture (*.jpg);;Portable Network Graphics (*.png)</source>
        <translation type="obsolete">JPEG Bild (*.jpg);;Portable Network Graphics (*.png)</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="91"/>
        <location filename="../PictureExport.cpp" line="44"/>
        <location filename="../PictureExport.cpp" line="127"/>
        <location filename="../PictureExport.cpp" line="131"/>
        <location filename="../PictureExport.cpp" line="145"/>
        <location filename="../PictureExport.cpp" line="151"/>
        <source>Export picture</source>
        <translation>Bild exportieren</translation>
    </message>
    <message>
        <source>Snapmatic Picture Exporter</source>
        <translation type="obsolete">Snapmatic Bild Exporter</translation>
    </message>
    <message>
        <source>Failed to save the picture</source>
        <translation type="obsolete">Beim Speichern des Bildes ist ein Fehler aufgetreten</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="91"/>
        <location filename="../PictureExport.cpp" line="151"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
</context>
<context>
    <name>ProfileInterface</name>
    <message>
        <location filename="../ProfileInterface.ui" line="14"/>
        <source>Profile Interface</source>
        <translation>Profil Interface</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="52"/>
        <source>Loading file %1 of %2 files</source>
        <oldsource>Loading %1 files of %2 files</oldsource>
        <translation>Lade Datei %1 von %2 Dateien</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="179"/>
        <location filename="../ProfileInterface.cpp" line="184"/>
        <location filename="../ProfileInterface.cpp" line="218"/>
        <location filename="../ProfileInterface.cpp" line="233"/>
        <location filename="../ProfileInterface.cpp" line="261"/>
        <location filename="../ProfileInterface.cpp" line="268"/>
        <location filename="../ProfileInterface.cpp" line="274"/>
        <location filename="../ProfileInterface.cpp" line="289"/>
        <location filename="../ProfileInterface.cpp" line="299"/>
        <location filename="../ProfileInterface.cpp" line="335"/>
        <location filename="../ProfileInterface.cpp" line="341"/>
        <source>Import copy</source>
        <translation>Kopie importieren</translation>
    </message>
    <message>
        <source>Content of Profile %1</source>
        <translation type="obsolete">Inhalt vom Profil %1</translation>
    </message>
    <message>
        <source>View</source>
        <translation type="obsolete">Ansehen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="189"/>
        <source>Close Profile</source>
        <translation>Profil schließen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="92"/>
        <source>Loading...</source>
        <translation>Lade...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="188"/>
        <source>All profile files (SGTA* PGTA*)</source>
        <translation>Alle Profildateien (SGTA* PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="189"/>
        <source>Savegames files (SGTA*)</source>
        <translation>Spielstanddateien (SGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="190"/>
        <source>Snapmatic pictures (PGTA*)</source>
        <translation>Snapmatic Bilder (PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="191"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="218"/>
        <source>Failed to read Snapmatic picture</source>
        <translation>Fehler beim Lesen vom Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="233"/>
        <source>Failed to read Savegame file</source>
        <translation>Fehler beim Lesen von Spielstanddatei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="261"/>
        <source>Can&apos;t import %1 because of not valid file format</source>
        <translation>Kann %1 nicht importieren weil das Dateiformat nicht gültig ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="268"/>
        <location filename="../ProfileInterface.cpp" line="274"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="289"/>
        <source>Failed to import copy of Snapmatic picture because the file not begin with PGTA</source>
        <translation>Fehlgeschlagenen beim Import vom Snapmatic Bild weil die Datei nicht mit PGTA begint </translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="299"/>
        <source>Failed to import copy of Snapmatic picture because the copy failed</source>
        <translation>Fehlgeschlagenen beim Import vom Snapmatic Bild weil kopieren fehlgeschlagen ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="335"/>
        <source>Failed to import copy of Savegame file because the copy failed</source>
        <translation>Fehlgeschlagenen beim Import vom Spielstand weil kopieren fehlgeschlagen ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="341"/>
        <source>Failed to import copy of Savegame file because no free Savegame slot left</source>
        <translation>Fehlgeschlagenen beim Import vom Spielstand weil kein Spielstandslot mehr übrig ist</translation>
    </message>
</context>
<context>
    <name>SavegameDialog</name>
    <message>
        <location filename="../SavegameDialog.ui" line="14"/>
        <location filename="../SavegameDialog.cpp" line="24"/>
        <source>Savegame Viewer</source>
        <translation>Spielstandanzeiger</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="20"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Savegame&lt;/span&gt;&lt;br&gt;&lt;br&gt;%1</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;Spielstand&lt;/span&gt;&lt;br&gt;&lt;br&gt;%1</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="58"/>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="65"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.cpp" line="24"/>
        <source>Failed at %1</source>
        <translation>Fehlgeschlagen bei %1</translation>
    </message>
</context>
<context>
    <name>SavegameWidget</name>
    <message>
        <location filename="../SavegameWidget.ui" line="14"/>
        <source>Savegame Widget</source>
        <translation>Spielstand Widget</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="67"/>
        <source>The Third Way (100%) - 00/00/00 00:00:00</source>
        <translation>The Third Way (100%) - 00/00/00 00:00:00</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="77"/>
        <location filename="../SavegameWidget.cpp" line="170"/>
        <source>View</source>
        <translation>Ansehen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="84"/>
        <location filename="../SavegameWidget.cpp" line="171"/>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="94"/>
        <location filename="../SavegameWidget.cpp" line="172"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="80"/>
        <location filename="../SavegameWidget.cpp" line="93"/>
        <source>Delete savegame</source>
        <translation>Savegame löschen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="80"/>
        <source>Are you sure to delete %1 from your savegames?</source>
        <translation>Bist du sicher %1 von deinen Spielständen zu löschen?</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="93"/>
        <source>Failed at deleting %1 from your savegames</source>
        <translation>Fehlgeschlagen beim Löschen %1 von deinen Spielständen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="176"/>
        <location filename="../SavegameWidget.cpp" line="184"/>
        <source>Select</source>
        <translation>Auswählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="177"/>
        <source>Deselect</source>
        <translation>Abwählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="178"/>
        <location filename="../SavegameWidget.cpp" line="185"/>
        <source>Select all</source>
        <translation>Alles auswählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="178"/>
        <location filename="../SavegameWidget.cpp" line="185"/>
        <source>Ctrl+S</source>
        <translation>Strg+S</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="179"/>
        <source>Deselect all</source>
        <translation>Alles abwählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="179"/>
        <source>Shift+S</source>
        <translation>Umschalt+S</translation>
    </message>
    <message>
        <source>View savegame</source>
        <translation type="obsolete">Spielstand ansehen</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="68"/>
        <location filename="../SavegameCopy.cpp" line="72"/>
        <location filename="../SavegameCopy.cpp" line="85"/>
        <location filename="../SavegameCopy.cpp" line="91"/>
        <source>Copy savegame</source>
        <translation>Spielstand kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="49"/>
        <source>Savegame files (SGTA*)</source>
        <translation>Spielstanddateien (SGTA*)</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="50"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="68"/>
        <source>Overwrite %1 with current savegame?</source>
        <translation>Überschreibe %1 mit aktuellen Spielstand?</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="72"/>
        <source>Failed to overwrite %1 with current savegame</source>
        <translation>Fehlgeschlagen beim Überschreiben von %1 mit aktuellen Spielstand </translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="85"/>
        <source>Failed to copy current savegame</source>
        <translation>Fehlgeschlagen beim Kopieren vom Spielstand</translation>
    </message>
    <message>
        <source>Failed to copy the savegame</source>
        <translation type="obsolete">Beim Kopieren vom Spielstand ist ein Fehler aufgetreten</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="91"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
    <message>
        <source>Are you sure to delete %1 from your Savegames?</source>
        <translation type="obsolete">Bist du sicher %1 von deinen Spielständen zu löschen?</translation>
    </message>
    <message>
        <source>Failed at deleting %1 from your Savegames</source>
        <translation type="obsolete">Fehlgeschlagen beim Löschen %1 von deinen Spielständen</translation>
    </message>
</context>
<context>
    <name>SnapmaticWidget</name>
    <message>
        <location filename="../SnapmaticWidget.ui" line="14"/>
        <source>Snapmatic Widget</source>
        <translation>Snapmatic Widget</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="82"/>
        <source>PHOTO - 00/00/00 00:00:00</source>
        <translation>FOTO - 00/00/00 00:00:00</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="92"/>
        <location filename="../SnapmaticWidget.cpp" line="177"/>
        <source>View</source>
        <translation>Ansehen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="102"/>
        <location filename="../SnapmaticWidget.cpp" line="178"/>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="109"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="116"/>
        <location filename="../SnapmaticWidget.cpp" line="179"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="101"/>
        <location filename="../SnapmaticWidget.cpp" line="114"/>
        <source>Delete picture</source>
        <translation>Bild löschen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="101"/>
        <source>Are you sure to delete %1 from your Snapmatic pictures?</source>
        <translation>Bist du sicher %1 von deinen Snapmatic Bilder zu löschen?</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="183"/>
        <location filename="../SnapmaticWidget.cpp" line="191"/>
        <source>Select</source>
        <translation>Auswählen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="184"/>
        <source>Deselect</source>
        <translation>Abwählen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="185"/>
        <location filename="../SnapmaticWidget.cpp" line="192"/>
        <source>Select all</source>
        <translation>Alles auswählen</translation>
    </message>
    <message>
        <source>Ctrl+S</source>
        <translation type="obsolete">Strg+S</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="186"/>
        <source>Deselect all</source>
        <translation>Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <source>View picture</source>
        <translation type="obsolete">Bild ansehen</translation>
    </message>
    <message>
        <source>Copy picture</source>
        <translation type="obsolete">Bild kopieren</translation>
    </message>
    <message>
        <source>Export picture</source>
        <translation type="obsolete">Bild exportieren</translation>
    </message>
    <message>
        <source>You&apos;re sure to delete %1 from your Snapmatic pictures?</source>
        <translation type="obsolete">Bist du sicher %1 von deinen Snapmatic Bilder zu löschen?</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="114"/>
        <source>Failed at deleting %1 from your Snapmatic pictures</source>
        <translation>Fehlgeschlagen beim Löschen %1 von deinen Snapmatic Bildern</translation>
    </message>
</context>
<context>
    <name>UserInterface</name>
    <message>
        <source>Grand Theft Auto V Sync</source>
        <translation type="obsolete">Grand Theft Auto V Sync</translation>
    </message>
    <message>
        <source>GTA V Sync</source>
        <translation type="obsolete">GTA V Sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="20"/>
        <source>gta5sync - %1</source>
        <translation>gta5sync - %1</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="86"/>
        <source>File</source>
        <translation>Datei</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="93"/>
        <source>Help</source>
        <translation>Hilfe</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="99"/>
        <source>Edit</source>
        <translation>Bearbeiten</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="103"/>
        <source>Profile</source>
        <translation>Profil</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="121"/>
        <source>About gta5sync</source>
        <translation>Über gta5sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="124"/>
        <source>Ctrl+A</source>
        <translation>Strg+A</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="129"/>
        <location filename="../UserInterface.cpp" line="128"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="145"/>
        <source>Options</source>
        <translation>Optionen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="148"/>
        <source>Ctrl+O</source>
        <translation>Strg+O</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="153"/>
        <source>Select all</source>
        <translation>Alles auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="156"/>
        <source>Ctrl+S</source>
        <translation>Strg+S</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="161"/>
        <source>Deselect all</source>
        <translation>Alles abwählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="164"/>
        <source>Shift+S</source>
        <translation>Umschalt+S</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="169"/>
        <source>Export selected</source>
        <translation>Auswahl exportieren</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="172"/>
        <source>Ctrl+E</source>
        <translation>Strg+E</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="177"/>
        <source>Delete selected</source>
        <translation>Auswahl löschen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="180"/>
        <source>Ctrl+D</source>
        <translation>Strg+D</translation>
    </message>
    <message>
        <source>Exit</source>
        <translation type="obsolete">Schließen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="132"/>
        <source>Ctrl+Q</source>
        <translation>Strg+Q</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="59"/>
        <location filename="../UserInterface.ui" line="137"/>
        <location filename="../UserInterface.cpp" line="47"/>
        <location filename="../UserInterface.cpp" line="181"/>
        <source>Select profile</source>
        <translation>Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="140"/>
        <source>Ctrl+P</source>
        <translation>Strg+P</translation>
    </message>
    <message>
        <source>GTA V Folder not found!</source>
        <translation type="obsolete">GTA V Ordner nicht gefunden!</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="72"/>
        <source>gta5sync</source>
        <translation>gta5sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="72"/>
        <source>Grand Theft Auto V Folder not found!</source>
        <translation>Grand Theft Auto V Ordner wurde nicht gefunden!</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="101"/>
        <source>Reload</source>
        <translation>Neuladen</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="148"/>
        <source>Reload profiles</source>
        <translation>Profile neuladen</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="148"/>
        <source>Not able to reload profiles</source>
        <translation>Nicht fähig Profile neuzuladen</translation>
    </message>
</context>
</TS>
