<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="de_DE">
<context>
    <name>AboutDialog</name>
    <message>
        <location filename="../AboutDialog.ui" line="14"/>
        <source>About gta5sync</source>
        <translation>Über gta5sync</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="100"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>generated by class</source>
        <translation type="obsolete">Generiert von der Klasse</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;&lt;br/&gt;Project version: %1&lt;br/&gt;Compiled with Qt %2&lt;br/&gt;Running with Qt %3&lt;br/&gt;&lt;br/&gt;Copyright © &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;&lt;br/&gt;Projektversion: %1&lt;br/&gt;Gebaut mit Qt %2&lt;br/&gt;Läuft auf Qt %3&lt;br/&gt;&lt;br/&gt;Copyright © &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="obsolete">Schließen</translation>
    </message>
    <message>
        <location filename="../AboutDialog.ui" line="65"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;A project for viewing and sync Grand Theft Auto 5 Snapmatic Pictures and Savegames&lt;br/&gt;&lt;br/&gt;Project version: %1&lt;br/&gt;Compiled with Qt %2&lt;br/&gt;Running with Qt %3&lt;br/&gt;&lt;br/&gt;Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is licensed under &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;gta5sync&lt;/span&gt;&lt;br/&gt;&lt;br/&gt;Ein Projekt zum ansehen und synchronisieren von Grand Theft Auto 5 Snapmatic Bilder und Spielständen&lt;br/&gt;&lt;br/&gt;Projektversion: %1&lt;br/&gt;Gebaut mit Qt %2&lt;br/&gt;Läuft auf Qt %3&lt;br/&gt;&lt;br/&gt;Copyright &amp;copy; &lt;a href=&quot;https://github.com/Syping/&quot;&gt;Syping&lt;/a&gt; 2016&lt;br/&gt;gta5sync is lizenziert unter &lt;a href=&quot;https://www.gnu.org/licenses/gpl-3.0.html#content&quot;&gt;GNU GPLv3&lt;/a&gt;</translation>
    </message>
</context>
<context>
    <name>OptionsDialog</name>
    <message>
        <source>Options</source>
        <translation>Optionen</translation>
    </message>
    <message>
        <source>gta5sync - Options</source>
        <translation>gta5sync - Optionen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="14"/>
        <source>gta5sync - Settings</source>
        <translation>gta5sync - Einstellungen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="27"/>
        <source>Profile</source>
        <translation>Profil</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="33"/>
        <source>Content Open/Select Mode</source>
        <translation>Inhalte Öffnen/Auswählen Modus</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="39"/>
        <source>Open with Singleclick</source>
        <translation>Ein Klick zum öffnen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="49"/>
        <source>Open with Doubleclick</source>
        <translation>Doppelklick zum öffnen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="56"/>
        <source>Select with Singleclick</source>
        <translation>Ein Klick zum auswählen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="66"/>
        <source>Default Profile</source>
        <translation>Standardprofil</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="92"/>
        <source>Players</source>
        <translation>Spieler</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="132"/>
        <source>ID</source>
        <translation>ID</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="137"/>
        <source>Name</source>
        <translation>Name</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="146"/>
        <location filename="../OptionsDialog.ui" line="152"/>
        <source>Language</source>
        <translation>Sprache</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="178"/>
        <source>Sync</source>
        <translation>Sync</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="184"/>
        <source>Sync is not implemented at current time</source>
        <translation>Sync wurde bisher nicht implementiert</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="216"/>
        <source>&amp;OK</source>
        <extracomment>OK, Cancel, Apply</extracomment>
        <translation>&amp;OK</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.ui" line="223"/>
        <source>&amp;Cancel</source>
        <extracomment>OK, Cancel, Apply</extracomment>
        <translation>Abbre&amp;chen</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="84"/>
        <source>%1 (%2 if available) [sys]</source>
        <comment>System like PC System = %1, System Language like Deutsch = %2</comment>
        <translation>%1 (%2 wenn verfügbar) [sys]</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="84"/>
        <source>System</source>
        <comment>System like PC System</comment>
        <translation>System</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="183"/>
        <source>%1</source>
        <comment>%1</comment>
        <translation>%1</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="183"/>
        <source>The language change will take effect after you restart %1.</source>
        <translation>Die Änderung der Sprache nimmt Effekt sobald du %1 neugestartet hast.</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="193"/>
        <source>No Profile</source>
        <comment>No Profile, as default</comment>
        <translation>Kein Profil</translation>
    </message>
    <message>
        <location filename="../OptionsDialog.cpp" line="201"/>
        <location filename="../OptionsDialog.cpp" line="204"/>
        <source>Profile: %1</source>
        <translation>Profil: %1</translation>
    </message>
</context>
<context>
    <name>PictureDialog</name>
    <message>
        <location filename="../PictureDialog.ui" line="14"/>
        <source>%1 - Snapmatic Picture Viewer</source>
        <translation>%1 - Snapmatic Bildansicht</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="129"/>
        <location filename="../PictureCopy.cpp" line="47"/>
        <location filename="../PictureExport.cpp" line="47"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="145"/>
        <source>&amp;Close</source>
        <translation>&amp;Schließen</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Picture Title: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation type="obsolete">&lt;span style=&quot; font-weight:600;&quot;&gt;Bildtitel: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="78"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Title: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Location: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Players: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;Titel: &lt;/span&gt;%6&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Standort: &lt;/span&gt;%1, %2, %3 &lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Spieler: &lt;/span&gt;%4&lt;br&gt;
&lt;span style=&quot; font-weight:600;&quot;&gt;Crew ID: &lt;/span&gt;%5</translation>
    </message>
    <message>
        <source>Export</source>
        <translation type="obsolete">Exportieren</translation>
    </message>
    <message>
        <source>Copy</source>
        <translation type="obsolete">Kopieren</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="142"/>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="65"/>
        <source>Export as &amp;JPG picture...</source>
        <translation>Exportiere als &amp;JPG Bild...</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="66"/>
        <source>Export as &amp;GTA Snapmatic...</source>
        <translation>Exportiere als &amp;GTA Snapmatic...</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="139"/>
        <location filename="../PictureDialog.cpp" line="186"/>
        <source>Snapmatic Picture Viewer</source>
        <translation>Snapmatic Bildansicht</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="139"/>
        <location filename="../PictureDialog.cpp" line="186"/>
        <source>Failed at %1</source>
        <translation>Fehlgeschlagen bei %1</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="175"/>
        <location filename="../PictureDialog.cpp" line="185"/>
        <source>No player</source>
        <translation>Keine Spieler</translation>
    </message>
    <message>
        <location filename="../PictureDialog.cpp" line="178"/>
        <location filename="../PictureDialog.cpp" line="185"/>
        <source>No crew</source>
        <translation>Keine Crew</translation>
    </message>
    <message>
        <source>Export picture...</source>
        <translation type="obsolete">Exportiere Bild...</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="46"/>
        <source>Export as JPG picture...</source>
        <translation>Exportiere als JPG Bild...</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="50"/>
        <source>JPEG picture (*.jpg)</source>
        <translation>JPEG Bild (*.jpg)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="51"/>
        <source>Portable Network Graphics (*.png)</source>
        <translation>Portable Network Graphics (*.png)</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="103"/>
        <location filename="../PictureExport.cpp" line="107"/>
        <location filename="../PictureExport.cpp" line="121"/>
        <location filename="../PictureExport.cpp" line="127"/>
        <source>Export as JPG picture</source>
        <translation>Exportiere als JPG Bild</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="69"/>
        <location filename="../PictureExport.cpp" line="103"/>
        <source>Overwrite %1 with current Snapmatic picture?</source>
        <translation>Überschreibe %1 mit aktuellen Snapmatic Bild?</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="69"/>
        <location filename="../PictureCopy.cpp" line="73"/>
        <location filename="../PictureCopy.cpp" line="86"/>
        <location filename="../PictureCopy.cpp" line="92"/>
        <source>Export as GTA Snapmatic</source>
        <translation>Exportiere als GTA Snapmatic</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="73"/>
        <location filename="../PictureExport.cpp" line="107"/>
        <source>Failed to overwrite %1 with current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Überschreiben von %1 mit aktuellen Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../PictureExport.cpp" line="121"/>
        <source>Failed to export current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Exportieren vom aktuellen Snapmatic Bild</translation>
    </message>
    <message>
        <source>Copy picture</source>
        <translation type="obsolete">Bild kopieren</translation>
    </message>
    <message>
        <source>Export picture for Import...</source>
        <translation type="obsolete">Exporti</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="46"/>
        <source>Export as GTA Snapmatic...</source>
        <translation>Exportiere als GTA Snapmatic...</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="50"/>
        <source>Snapmatic pictures (PGTA*)</source>
        <translation>Snapmatic Bilder (PGTA*)</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="51"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="86"/>
        <source>Failed to copy current Snapmatic picture</source>
        <translation>Fehlgeschlagen beim Kopieren vom Snapmatic Bild</translation>
    </message>
    <message>
        <source>Failed to save current picture</source>
        <translation type="obsolete">Fehlgeschlagen beim Speichern vom aktuellen Bild</translation>
    </message>
    <message>
        <source>JPEG picture (*.jpg);;Portable Network Graphics (*.png)</source>
        <translation type="obsolete">JPEG Bild (*.jpg);;Portable Network Graphics (*.png)</translation>
    </message>
    <message>
        <location filename="../PictureDialog.ui" line="126"/>
        <source>Export picture</source>
        <translation>Bild exportieren</translation>
    </message>
    <message>
        <source>Snapmatic Picture Exporter</source>
        <translation type="obsolete">Snapmatic Bild Exporter</translation>
    </message>
    <message>
        <source>Failed to save the picture</source>
        <translation type="obsolete">Beim Speichern des Bildes ist ein Fehler aufgetreten</translation>
    </message>
    <message>
        <location filename="../PictureCopy.cpp" line="92"/>
        <location filename="../PictureExport.cpp" line="127"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
</context>
<context>
    <name>ProfileInterface</name>
    <message>
        <location filename="../ProfileInterface.ui" line="14"/>
        <source>Profile Interface</source>
        <translation>Profil Interface</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="55"/>
        <source>Loading file %1 of %2 files</source>
        <oldsource>Loading %1 files of %2 files</oldsource>
        <translation>Lade Datei %1 von %2 Dateien</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="182"/>
        <source>Import exported file</source>
        <translation>Importiere exportierte Datei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="185"/>
        <source>&amp;Import...</source>
        <translation>&amp;Importieren...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="195"/>
        <source>Close profile</source>
        <translation>Profil schließen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.ui" line="198"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>Import copy</source>
        <translation type="obsolete">Kopie importieren</translation>
    </message>
    <message>
        <source>Content of Profile %1</source>
        <translation type="obsolete">Inhalt vom Profil %1</translation>
    </message>
    <message>
        <source>View</source>
        <translation type="obsolete">Ansehen</translation>
    </message>
    <message>
        <source>Close Profile</source>
        <translation type="obsolete">Profil schließen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="102"/>
        <source>Loading...</source>
        <translation>Lade...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="355"/>
        <source>Import...</source>
        <translation>Importieren...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="356"/>
        <location filename="../ProfileInterface.cpp" line="396"/>
        <location filename="../ProfileInterface.cpp" line="401"/>
        <location filename="../ProfileInterface.cpp" line="426"/>
        <location filename="../ProfileInterface.cpp" line="443"/>
        <location filename="../ProfileInterface.cpp" line="473"/>
        <location filename="../ProfileInterface.cpp" line="478"/>
        <location filename="../ProfileInterface.cpp" line="488"/>
        <location filename="../ProfileInterface.cpp" line="499"/>
        <location filename="../ProfileInterface.cpp" line="536"/>
        <location filename="../ProfileInterface.cpp" line="542"/>
        <source>Import</source>
        <translation>Importieren</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="359"/>
        <location filename="../UserInterface.cpp" line="312"/>
        <source>All profile files (SGTA* PGTA*)</source>
        <translation>Alle Profildateien (SGTA* PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="360"/>
        <location filename="../UserInterface.cpp" line="313"/>
        <source>Savegames files (SGTA*)</source>
        <translation>Spielstanddateien (SGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="361"/>
        <location filename="../UserInterface.cpp" line="314"/>
        <source>Snapmatic pictures (PGTA*)</source>
        <translation>Snapmatic Bilder (PGTA*)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="362"/>
        <location filename="../UserInterface.cpp" line="315"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="396"/>
        <source>Import failed with...

%1</source>
        <translation>Importieren fehlgeschlagen mit...

%1</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="426"/>
        <location filename="../UserInterface.cpp" line="351"/>
        <source>Failed to read Snapmatic picture</source>
        <translation>Fehler beim Lesen vom Snapmatic Bild</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="443"/>
        <location filename="../UserInterface.cpp" line="367"/>
        <source>Failed to read Savegame file</source>
        <translation>Fehler beim Lesen von Spielstanddatei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="473"/>
        <source>Can&apos;t import %1 because of not valid file format</source>
        <translation>Kann %1 nicht importieren weil das Dateiformat nicht gültig ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="639"/>
        <source>%1Export Snapmatic pictures%2&lt;br&gt;&lt;br&gt;JPG pictures make it possible to open the picture with a Image Viewer&lt;br&gt;GTA Snapmatic make it possible to import the picture into the game&lt;br&gt;&lt;br&gt;Export as:</source>
        <translation>%1Exportiere Snapmatic Bilder%2&lt;br&gt;&lt;br&gt;JPG Bilder machen es möglich sie mit ein Bildansicht Programm zu öffnen&lt;br&gt;Das GTA Snapmatic Format macht es möglich sie wieder ins Game zu importieren&lt;br&gt;&lt;br&gt;Exportieren als:</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="401"/>
        <location filename="../ProfileInterface.cpp" line="478"/>
        <location filename="../UserInterface.cpp" line="399"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="488"/>
        <source>Failed to import the Snapmatic picture, file not begin with PGTA</source>
        <translation>Fehlgeschlagen beim Importieren vom Snapmatic Bild, Datei beginnt nicht mit PGTA</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="499"/>
        <source>Failed to import the Snapmatic picture, can&apos;t copy the file into profile</source>
        <translation>Fehlgeschlagen beim Importieren vom Snapmatic Bild, kann Snapmatic Bild nicht ins Profil kopieren </translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="536"/>
        <source>Failed to import the Savegame, can&apos;t copy the file into profile</source>
        <translation>Fehlgeschlagen beim Importieren vom Spielstand, kann Spielstanddatei nicht ins Profil kopieren</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="542"/>
        <source>Failed to import the Savegame, no Savegame slot is left</source>
        <translation>Fehlgeschlagen beim Importieren vom Spielstand, kein Spielstandslot mehr frei</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="624"/>
        <location filename="../ProfileInterface.cpp" line="642"/>
        <source>JPG pictures and GTA Snapmatic</source>
        <translation>JPG Bilder und GTA Snapmatic</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="625"/>
        <location filename="../ProfileInterface.cpp" line="647"/>
        <source>JPG pictures only</source>
        <translation>Nur JPG Bilder</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="626"/>
        <location filename="../ProfileInterface.cpp" line="651"/>
        <source>GTA Snapmatic only</source>
        <translation>Nur GTA Snapmatic</translation>
    </message>
    <message>
        <source>Export Snapmatic pictures

JPG pictures make it possible to open the picture with a Image Viewer
GTA Snapmatic make it possible to import the picture into the game

Export as:</source>
        <translation>Exportiere Snapmatic Bilder

JPG Bilder machen es möglich sie mit ein Bildansicht Programm zu öffnen
Das GTA Snapmatic Format macht es möglich sie wieder ins Game zu importieren

Exportieren als:</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="736"/>
        <location filename="../ProfileInterface.cpp" line="780"/>
        <source>No Snapmatic pictures or Savegames files are selected</source>
        <translation>Keine Snapmatic Bilder oder Spielstände ausgewählt</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="744"/>
        <location filename="../ProfileInterface.cpp" line="774"/>
        <location filename="../ProfileInterface.cpp" line="780"/>
        <source>Remove selected</source>
        <translation>Auswahl löschen</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="744"/>
        <source>You really want remove the selected Snapmatic picutres and Savegame files?</source>
        <translation>Möchtest du wirklich die ausgewählten Snapmatic Bilder und Spielstanddateien löschen?</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="774"/>
        <source>Failed at remove the complete selected Snapmatic pictures and/or Savegame files</source>
        <translation>Fehlgeschlagen beim kompletten entfernen der ausgewählten Snapmatic Bilder und/oder der Spielstanddateien</translation>
    </message>
    <message>
        <source>Failed to import copy of Snapmatic picture because the file not begin with PGTA</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Snapmatic Bild weil die Datei nicht mit PGTA begint </translation>
    </message>
    <message>
        <source>Failed to import copy of Snapmatic picture because the copy failed</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Snapmatic Bild weil kopieren fehlgeschlagen ist</translation>
    </message>
    <message>
        <source>Failed to import copy of Savegame file because the copy failed</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Spielstand weil kopieren fehlgeschlagen ist</translation>
    </message>
    <message>
        <source>Failed to import copy of Savegame file because no free Savegame slot left</source>
        <translation type="obsolete">Fehlgeschlagenen beim Import vom Spielstand weil kein Spielstandslot mehr übrig ist</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="602"/>
        <location filename="../ProfileInterface.cpp" line="639"/>
        <location filename="../ProfileInterface.cpp" line="716"/>
        <location filename="../ProfileInterface.cpp" line="736"/>
        <source>Export selected</source>
        <translation>Auswahl exportieren</translation>
    </message>
    <message>
        <source>Export and Copy pictures</source>
        <translation type="obsolete">Bilder exportieren und kopieren</translation>
    </message>
    <message>
        <source>Export pictures</source>
        <translation type="obsolete">Bilder exportieren</translation>
    </message>
    <message>
        <source>Copy pictures</source>
        <translation type="obsolete">Bilder kopieren</translation>
    </message>
    <message>
        <source>How should we deal with the Snapmatic pictures?</source>
        <translation type="obsolete">Wie sollen wir mit den Snapmatic Bilder umgehen?</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="682"/>
        <source>Export selected...</source>
        <translation>Auswahl exportieren...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="683"/>
        <source>Initializing export...</source>
        <translation>Initialisiere Export...</translation>
    </message>
    <message>
        <source>Initializing...</source>
        <translation type="obsolete">Initialisierung...</translation>
    </message>
    <message>
        <location filename="../ProfileInterface.cpp" line="716"/>
        <source>Export failed with...

%1</source>
        <translation>Exportieren fehlgeschlagen bei...\n%1</translation>
    </message>
    <message>
        <source>Delete selected</source>
        <translation type="obsolete">Auswahl löschen</translation>
    </message>
    <message>
        <source>You really want delete the selected content?</source>
        <translation type="obsolete">Möchtest du wirklich den ausgewählten Inhalt löschen?</translation>
    </message>
    <message>
        <source>Failed at delete all selected content</source>
        <translation type="obsolete">Fehlgeschlagen beim Löschen von alle ausgewählte Inhalte</translation>
    </message>
    <message>
        <source>Current export job: %1</source>
        <translation type="obsolete">Aktueller Exportiervorgang: %1</translation>
    </message>
    <message>
        <location filename="../ExportThread.cpp" line="50"/>
        <location filename="../ExportThread.cpp" line="65"/>
        <location filename="../ExportThread.cpp" line="86"/>
        <source>Export file %1 of %2 files</source>
        <translation>Exportiere Datei %1 von %2 Dateien</translation>
    </message>
</context>
<context>
    <name>SavegameDialog</name>
    <message>
        <location filename="../SavegameDialog.ui" line="14"/>
        <location filename="../SavegameDialog.cpp" line="24"/>
        <source>Savegame Viewer</source>
        <translation>Spielstandanzeiger</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="26"/>
        <source>&lt;span style=&quot; font-weight:600;&quot;&gt;Savegame&lt;/span&gt;&lt;br&gt;&lt;br&gt;%1</source>
        <translation>&lt;span style=&quot; font-weight:600;&quot;&gt;Spielstand&lt;/span&gt;&lt;br&gt;&lt;br&gt;%1</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="54"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <source>Cop&amp;y</source>
        <translation>&amp;Kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.ui" line="61"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <source>Close</source>
        <translation>Schließen</translation>
    </message>
    <message>
        <location filename="../SavegameDialog.cpp" line="24"/>
        <source>Failed at %1</source>
        <translation>Fehlgeschlagen bei %1</translation>
    </message>
</context>
<context>
    <name>SavegameWidget</name>
    <message>
        <location filename="../SavegameWidget.ui" line="14"/>
        <source>Savegame Widget</source>
        <translation>Spielstand Widget</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="67"/>
        <source>The Third Way (100%) - 00/00/00 00:00:00</source>
        <translation>The Third Way (100%) - 00/00/00 00:00:00</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="80"/>
        <source>View</source>
        <translation>Ansehen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="90"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="103"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="100"/>
        <location filename="../SavegameWidget.cpp" line="101"/>
        <location filename="../SavegameWidget.cpp" line="114"/>
        <source>Delete savegame</source>
        <translation>Savegame löschen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="49"/>
        <source>Export Savegame...</source>
        <translation>Spielstand exportieren...</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="101"/>
        <source>Are you sure to delete %1 from your savegames?</source>
        <translation>Bist du sicher %1 von deinen Spielständen zu löschen?</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="114"/>
        <source>Failed at deleting %1 from your savegames</source>
        <translation>Fehlgeschlagen beim Löschen %1 von deinen Spielständen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="178"/>
        <source>&amp;View</source>
        <translation>A&amp;nsehen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="180"/>
        <source>&amp;Remove</source>
        <translation>Entfe&amp;rnen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="184"/>
        <location filename="../SavegameWidget.cpp" line="192"/>
        <source>&amp;Select</source>
        <translation>Au&amp;swählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="185"/>
        <source>&amp;Deselect</source>
        <translation>A&amp;bwählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="186"/>
        <location filename="../SavegameWidget.cpp" line="193"/>
        <source>Select &amp;All</source>
        <translation>&amp;Alles auswählen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.cpp" line="187"/>
        <source>&amp;Deselect All</source>
        <translation>Alles a&amp;bwählen</translation>
    </message>
    <message>
        <source>Select</source>
        <translation type="obsolete">Auswählen</translation>
    </message>
    <message>
        <source>Deselect</source>
        <translation type="obsolete">Abwählen</translation>
    </message>
    <message>
        <source>Select all</source>
        <translation type="obsolete">Alles auswählen</translation>
    </message>
    <message>
        <source>Ctrl+S</source>
        <translation type="obsolete">Strg+S</translation>
    </message>
    <message>
        <source>Deselect all</source>
        <translation type="obsolete">Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="77"/>
        <source>View savegame</source>
        <translation>Spielstand ansehen</translation>
    </message>
    <message>
        <location filename="../SavegameWidget.ui" line="87"/>
        <source>Copy savegame</source>
        <translation>Spielstand kopieren</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="48"/>
        <location filename="../SavegameWidget.cpp" line="179"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="51"/>
        <source>Savegame files (SGTA*)</source>
        <translation>Spielstanddateien (SGTA*)</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="52"/>
        <source>All files (**)</source>
        <translation>Alle Dateien (**)</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="70"/>
        <location filename="../SavegameCopy.cpp" line="74"/>
        <location filename="../SavegameCopy.cpp" line="87"/>
        <location filename="../SavegameCopy.cpp" line="93"/>
        <source>Export Savegame</source>
        <translation>Spielstand exportieren</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="70"/>
        <source>Overwrite %1 with current Savegame?</source>
        <translation>Überschreibe %1 mit aktuellen Spielstand?</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="74"/>
        <source>Failed to overwrite %1 with current Savegame</source>
        <translation>Fehlgeschlagen beim Überschrieben von %1 mit aktuellen Spielstand</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="87"/>
        <source>Failed to export current Savegame</source>
        <translation>Fehlgeschlagen beim Exportieren vom aktuellen Spielstand</translation>
    </message>
    <message>
        <source>Failed to copy current Savegame</source>
        <translation type="obsolete">Fehlgeschlagen beim Kopieren vom aktuellen Spielstand</translation>
    </message>
    <message>
        <source>Overwrite %1 with current savegame?</source>
        <translation type="obsolete">Überschreibe %1 mit aktuellen Spielstand?</translation>
    </message>
    <message>
        <source>Failed to overwrite %1 with current savegame</source>
        <translation type="obsolete">Fehlgeschlagen beim Überschreiben von %1 mit aktuellen Spielstand </translation>
    </message>
    <message>
        <source>Failed to copy current savegame</source>
        <translation type="obsolete">Fehlgeschlagen beim Kopieren vom Spielstand</translation>
    </message>
    <message>
        <source>Failed to copy the savegame</source>
        <translation type="obsolete">Beim Kopieren vom Spielstand ist ein Fehler aufgetreten</translation>
    </message>
    <message>
        <location filename="../SavegameCopy.cpp" line="93"/>
        <source>No valid file is selected</source>
        <translation>Keine gültige Datei wurde ausgewählt</translation>
    </message>
    <message>
        <source>Are you sure to delete %1 from your Savegames?</source>
        <translation type="obsolete">Bist du sicher %1 von deinen Spielständen zu löschen?</translation>
    </message>
    <message>
        <source>Failed at deleting %1 from your Savegames</source>
        <translation type="obsolete">Fehlgeschlagen beim Löschen %1 von deinen Spielständen</translation>
    </message>
</context>
<context>
    <name>SnapmaticWidget</name>
    <message>
        <location filename="../SnapmaticWidget.ui" line="14"/>
        <source>Snapmatic Widget</source>
        <translation>Snapmatic Widget</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="82"/>
        <source>PHOTO - 00/00/00 00:00:00</source>
        <translation>FOTO - 00/00/00 00:00:00</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="95"/>
        <source>View</source>
        <translation>Ansehen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="108"/>
        <source>Copy</source>
        <translation>Kopieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="118"/>
        <source>Export</source>
        <translation>Exportieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="128"/>
        <source>Delete</source>
        <translation>Löschen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="125"/>
        <location filename="../SnapmaticWidget.cpp" line="128"/>
        <location filename="../SnapmaticWidget.cpp" line="141"/>
        <source>Delete picture</source>
        <translation>Bild löschen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="128"/>
        <source>Are you sure to delete %1 from your Snapmatic pictures?</source>
        <translation>Bist du sicher %1 von deinen Snapmatic Bilder zu löschen?</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="193"/>
        <source>&amp;Export</source>
        <translation>&amp;Exportieren</translation>
    </message>
    <message>
        <source>Export as &amp;JPG picture</source>
        <translation type="obsolete">Exportiere als &amp;JPG Bild</translation>
    </message>
    <message>
        <source>Export as &amp;GTA Snapmatic</source>
        <translation type="obsolete">Exportiere als &amp;GTA Snapmatic</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="195"/>
        <source>Export as &amp;JPG picture...</source>
        <translation>Exportiere als &amp;JPG Bild...</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="196"/>
        <source>Export as &amp;GTA Snapmatic...</source>
        <translation>Exportiere als &amp;GTA Snapmatic...</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="197"/>
        <source>&amp;View</source>
        <translation>A&amp;nsehen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="199"/>
        <source>&amp;Remove</source>
        <translation>Entfe&amp;rnen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="203"/>
        <location filename="../SnapmaticWidget.cpp" line="211"/>
        <source>&amp;Select</source>
        <translation>Au&amp;swählen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="204"/>
        <source>&amp;Deselect</source>
        <translation>A&amp;bwählen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="205"/>
        <location filename="../SnapmaticWidget.cpp" line="212"/>
        <source>Select &amp;All</source>
        <translation>Alles &amp;auswählen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="206"/>
        <source>&amp;Deselect All</source>
        <translation>Alles a&amp;bwählen</translation>
    </message>
    <message>
        <source>Select</source>
        <translation type="obsolete">Auswählen</translation>
    </message>
    <message>
        <source>Deselect</source>
        <translation type="obsolete">Abwählen</translation>
    </message>
    <message>
        <source>Select all</source>
        <translation type="obsolete">Alles auswählen</translation>
    </message>
    <message>
        <source>Ctrl+S</source>
        <translation type="obsolete">Strg+S</translation>
    </message>
    <message>
        <source>Deselect all</source>
        <translation type="obsolete">Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="92"/>
        <source>View picture</source>
        <translation>Bild ansehen</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="105"/>
        <source>Copy picture</source>
        <translation>Bild kopieren</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.ui" line="115"/>
        <source>Export picture</source>
        <translation>Bild exportieren</translation>
    </message>
    <message>
        <source>You&apos;re sure to delete %1 from your Snapmatic pictures?</source>
        <translation type="obsolete">Bist du sicher %1 von deinen Snapmatic Bilder zu löschen?</translation>
    </message>
    <message>
        <location filename="../SnapmaticWidget.cpp" line="141"/>
        <source>Failed at deleting %1 from your Snapmatic pictures</source>
        <translation>Fehlgeschlagen beim Löschen %1 von deinen Snapmatic Bildern</translation>
    </message>
</context>
<context>
    <name>UserInterface</name>
    <message>
        <source>Grand Theft Auto V Sync</source>
        <translation type="obsolete">Grand Theft Auto V Sync</translation>
    </message>
    <message>
        <source>GTA V Sync</source>
        <translation type="obsolete">GTA V Sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="20"/>
        <location filename="../UserInterface.cpp" line="57"/>
        <source>gta5sync - %1</source>
        <translation>gta5sync - %1</translation>
    </message>
    <message>
        <source>File</source>
        <translation type="obsolete">Datei</translation>
    </message>
    <message>
        <source>Help</source>
        <translation type="obsolete">Hilfe</translation>
    </message>
    <message>
        <source>Edit</source>
        <translation type="obsolete">Bearbeiten</translation>
    </message>
    <message>
        <source>Profile</source>
        <translation type="obsolete">Profil</translation>
    </message>
    <message>
        <source>About gta5sync</source>
        <translation type="obsolete">Über gta5sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="221"/>
        <source>Ctrl+A</source>
        <translation>Strg+A</translation>
    </message>
    <message>
        <source>Close</source>
        <translation type="obsolete">Schließen</translation>
    </message>
    <message>
        <source>Options</source>
        <translation type="obsolete">Optionen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="274"/>
        <source>Ctrl+O</source>
        <translation>Strg+O</translation>
    </message>
    <message>
        <source>Select all</source>
        <translation type="obsolete">Alles auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="210"/>
        <source>Ctrl+S</source>
        <translation>Strg+S</translation>
    </message>
    <message>
        <source>Deselect all</source>
        <translation type="obsolete">Alles abwählen</translation>
    </message>
    <message>
        <source>Shift+S</source>
        <translation type="obsolete">Umschalt+S</translation>
    </message>
    <message>
        <source>Export selected</source>
        <translation type="obsolete">Auswahl exportieren</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="243"/>
        <source>Ctrl+E</source>
        <translation>Strg+E</translation>
    </message>
    <message>
        <source>Delete selected</source>
        <translation type="obsolete">Auswahl löschen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="232"/>
        <source>Ctrl+D</source>
        <translation>Strg+D</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="188"/>
        <source>Exit</source>
        <translation>Beenden</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="185"/>
        <source>&amp;Exit</source>
        <translation>B&amp;eenden</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="191"/>
        <source>Ctrl+Q</source>
        <translation>Strg+Q</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="59"/>
        <source>Select profile</source>
        <translation>Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="136"/>
        <source>&amp;File</source>
        <translation>&amp;Datei</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="145"/>
        <source>&amp;Help</source>
        <translation>&amp;Hilfe</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="151"/>
        <source>&amp;Edit</source>
        <translation>Bearb&amp;eiten</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="157"/>
        <source>&amp;Profile</source>
        <translation>&amp;Profil</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="173"/>
        <source>&amp;About gta5sync</source>
        <translation>&amp;Über gta5sync</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="196"/>
        <source>Close &amp;Profile</source>
        <translation>&amp;Profil schließen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="199"/>
        <source>Ctrl+End</source>
        <translation>Strg+Ende</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="251"/>
        <source>Ctrl+Del</source>
        <translation>Strg+Entf</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="271"/>
        <source>&amp;Open File...</source>
        <translation>Datei &amp;öffnen...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="110"/>
        <source>&amp;Close</source>
        <translation>S&amp;chließen</translation>
    </message>
    <message>
        <source>Select &amp;Profile</source>
        <translation>&amp;Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="176"/>
        <source>Ctrl+P</source>
        <translation>Strg+P</translation>
    </message>
    <message>
        <source>&amp;Options</source>
        <translation>&amp;Optionen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="207"/>
        <source>&amp;Settings</source>
        <translation>Ein&amp;stellungen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="218"/>
        <source>Select &amp;All</source>
        <translation>&amp;Alles auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="229"/>
        <source>&amp;Deselect All</source>
        <translation>Alles a&amp;bwählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="240"/>
        <source>&amp;Export selected...</source>
        <translation>Auswahl &amp;exportieren...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="248"/>
        <source>&amp;Remove selected</source>
        <translation>Auswahl entfe&amp;rnen</translation>
    </message>
    <message>
        <source>Ctrl+R</source>
        <translation>Strg+R</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="259"/>
        <source>&amp;Import files...</source>
        <translation>Dateien &amp;importieren...</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="262"/>
        <source>Ctrl+I</source>
        <translation>Strg+I</translation>
    </message>
    <message>
        <source>GTA V Folder not found!</source>
        <translation type="obsolete">GTA V Ordner nicht gefunden!</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="59"/>
        <location filename="../UserInterface.cpp" line="199"/>
        <source>Select Profile</source>
        <translation>Profil auswählen</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="72"/>
        <location filename="../UserInterface.cpp" line="148"/>
        <source>Select GTA V Folder...</source>
        <translation>Wähle GTA V Ordner...</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="123"/>
        <source>Select GTA V &amp;Folder...</source>
        <translation>Wähle GTA V &amp;Ordner...</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="309"/>
        <source>Open File...</source>
        <translation>Datei öffnen...</translation>
    </message>
    <message>
        <source>Import</source>
        <translation>Importieren</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="351"/>
        <location filename="../UserInterface.cpp" line="367"/>
        <location filename="../UserInterface.cpp" line="394"/>
        <location filename="../UserInterface.cpp" line="399"/>
        <source>Open File</source>
        <translation>Datei öffnen</translation>
    </message>
    <message>
        <location filename="../UserInterface.cpp" line="394"/>
        <source>Can&apos;t open %1 because of not valid file format</source>
        <translation>Kann nicht %1 öffnen weil Dateiformat nicht gültig ist</translation>
    </message>
    <message>
        <source>Change GTA V &amp;Folder</source>
        <translation>GTA V &amp;Ordner ändern</translation>
    </message>
    <message>
        <source>gta5sync</source>
        <translation>gta5sync</translation>
    </message>
    <message>
        <source>Grand Theft Auto V Folder not found!</source>
        <translation>Grand Theft Auto V Ordner wurde nicht gefunden!</translation>
    </message>
    <message>
        <location filename="../UserInterface.ui" line="103"/>
        <source>&amp;Reload</source>
        <translation>&amp;Neuladen</translation>
    </message>
    <message>
        <source>Reload</source>
        <translation type="obsolete">Neuladen</translation>
    </message>
    <message>
        <source>Reload profiles</source>
        <translation>Profile neuladen</translation>
    </message>
    <message>
        <source>Not able to reload profiles</source>
        <translation>Nicht fähig Profile neuzuladen</translation>
    </message>
</context>
</TS>
